//HintName: Specular.Analyzers/Specular.Analyzers.SpecularProviderGenerator/SpecularScanReport.g.cs
#nullable enable
using System;
using System.Collections.Generic;
using System.Reflection;

namespace Specular;
[System.Runtime.CompilerServices.CompilerGenerated, Microsoft.CodeAnalysis.EmbeddedAttribute]
internal enum ScannerExpressionKind
{
    Assembly,
    Reflection,
    ServiceDescriptor
}

[System.Runtime.CompilerServices.CompilerGenerated, Microsoft.CodeAnalysis.EmbeddedAttribute, System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed record ScanReportType(string AssemblyName, string TypeName, string? Type);
[System.Runtime.CompilerServices.CompilerGenerated, Microsoft.CodeAnalysis.EmbeddedAttribute, System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed record ScanReportAssembly(string AssemblyName, Assembly? Assembly);
[System.Runtime.CompilerServices.CompilerGenerated, Microsoft.CodeAnalysis.EmbeddedAttribute, System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed record ScannerExpression(ScannerExpressionKind Kind, string FilePath, int LineNumber, IReadOnlyList<ScanReportAssembly> DiscoveredAssemblies, IReadOnlyList<ScanReportType> DiscoveredTypes);
[System.Runtime.CompilerServices.CompilerGenerated, Microsoft.CodeAnalysis.EmbeddedAttribute, System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal static class SpecularScanReport
{
    public static IReadOnlyList<ScannerExpression> Entries { get; } = new ScannerExpression[]
    {
        new(ScannerExpressionKind.Assembly, "Input0.cs", 16, new ScanReportAssembly[] { new("Specular", "typeof(global::Specular.ISpecularProvider).Assembly"), new("System.ComponentModel", "typeof(global::System.IServiceProvider).Assembly"), new("TestAssembly", "typeof(global::TestAssembly.IService).Assembly"), new("TestProject", "") }, new ScanReportType[] { }),
        new(ScannerExpressionKind.Assembly, "Input0.cs", 17, new ScanReportAssembly[] { new("Specular", "typeof(global::Specular.ISpecularProvider).Assembly"), new("System.ComponentModel", "typeof(global::System.IServiceProvider).Assembly"), new("TestAssembly", "typeof(global::TestAssembly.IService).Assembly"), new("TestProject", "") }, new ScanReportType[] { }),
        new(ScannerExpressionKind.Assembly, "Input0.cs", 18, new ScanReportAssembly[] { new("Specular", "typeof(global::Specular.ISpecularProvider).Assembly"), new("System.ComponentModel", "typeof(global::System.IServiceProvider).Assembly"), new("TestAssembly", "typeof(global::TestAssembly.IService).Assembly"), new("TestProject", "") }, new ScanReportType[] { }),
        new(ScannerExpressionKind.Assembly, "Input0.cs", 20, new ScanReportAssembly[] { new("TestProject", "") }, new ScanReportType[] { }),
        new(ScannerExpressionKind.Assembly, "Input0.cs", 21, new ScanReportAssembly[] { new("TestProject", "") }, new ScanReportType[] { }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 22, new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", "typeof(Specular.Abstractions.IReflectionAssemblySelector)"), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", "typeof(Specular.Abstractions.IReflectionTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", "typeof(Specular.Abstractions.IServiceDescriptorAssemblySelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", "typeof(Specular.Abstractions.IServiceDescriptorTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", "typeof(Specular.Abstractions.IServiceLifetimeSelector)"), new("Specular", "Specular.Abstractions.IServiceTypeSelector", "typeof(Specular.Abstractions.IServiceTypeSelector)"), new("Specular", "Specular.Abstractions.ITypeFilter", "typeof(Specular.Abstractions.ITypeFilter)"), new("Specular", "Specular.Abstractions.TypeInfoFilter", "typeof(Specular.Abstractions.TypeInfoFilter)"), new("Specular", "Specular.Abstractions.TypeKindFilter", "typeof(Specular.Abstractions.TypeKindFilter)"), new("Specular", "Specular.ScannerExpressionKind", ""), new("TestAssembly", "TestAssembly.IGenericService`1", "typeof(TestAssembly.IGenericService<T>)"), new("TestAssembly", "TestAssembly.IOther", "typeof(TestAssembly.IOther)"), new("TestAssembly", "TestAssembly.IRequestHandler`2", "typeof(TestAssembly.IRequestHandler<T, R>)"), new("TestAssembly", "TestAssembly.IRequest`1", "typeof(TestAssembly.IRequest<T>)"), new("TestAssembly", "TestAssembly.IService", "typeof(TestAssembly.IService)"), new("TestAssembly", "TestAssembly.IServiceB", "typeof(TestAssembly.IServiceB)"), new("TestAssembly", "TestAssembly.IValidator", "typeof(TestAssembly.IValidator)"), new("TestAssembly", "TestAssembly.IValidator`1", "typeof(TestAssembly.IValidator<T>)") }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 32, new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", "typeof(Specular.Abstractions.IReflectionAssemblySelector)"), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", "typeof(Specular.Abstractions.IReflectionTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", "typeof(Specular.Abstractions.IServiceDescriptorAssemblySelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", "typeof(Specular.Abstractions.IServiceDescriptorTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", "typeof(Specular.Abstractions.IServiceLifetimeSelector)"), new("Specular", "Specular.Abstractions.IServiceTypeSelector", "typeof(Specular.Abstractions.IServiceTypeSelector)"), new("Specular", "Specular.Abstractions.ITypeFilter", "typeof(Specular.Abstractions.ITypeFilter)"), new("TestAssembly", "TestAssembly.IGenericService`1", "typeof(TestAssembly.IGenericService<T>)"), new("TestAssembly", "TestAssembly.IOther", "typeof(TestAssembly.IOther)"), new("TestAssembly", "TestAssembly.IRequestHandler`2", "typeof(TestAssembly.IRequestHandler<T, R>)"), new("TestAssembly", "TestAssembly.IRequest`1", "typeof(TestAssembly.IRequest<T>)"), new("TestAssembly", "TestAssembly.IService", "typeof(TestAssembly.IService)"), new("TestAssembly", "TestAssembly.IServiceB", "typeof(TestAssembly.IServiceB)"), new("TestAssembly", "TestAssembly.IValidator", "typeof(TestAssembly.IValidator)"), new("TestAssembly", "TestAssembly.IValidator`1", "typeof(TestAssembly.IValidator<T>)") }),
        new(ScannerExpressionKind.Reflection, "{scrubbed}"),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 52, new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", "typeof(Specular.Abstractions.IReflectionAssemblySelector)"), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", "typeof(Specular.Abstractions.IReflectionTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", "typeof(Specular.Abstractions.IServiceDescriptorAssemblySelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", "typeof(Specular.Abstractions.IServiceDescriptorTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", "typeof(Specular.Abstractions.IServiceLifetimeSelector)"), new("Specular", "Specular.Abstractions.IServiceTypeSelector", "typeof(Specular.Abstractions.IServiceTypeSelector)"), new("Specular", "Specular.Abstractions.ITypeFilter", "typeof(Specular.Abstractions.ITypeFilter)"), new("TestAssembly", "TestAssembly.IGenericService`1", "typeof(TestAssembly.IGenericService<T>)"), new("TestAssembly", "TestAssembly.IOther", "typeof(TestAssembly.IOther)"), new("TestAssembly", "TestAssembly.IRequestHandler`2", "typeof(TestAssembly.IRequestHandler<T, R>)"), new("TestAssembly", "TestAssembly.IRequest`1", "typeof(TestAssembly.IRequest<T>)"), new("TestAssembly", "TestAssembly.IService", "typeof(TestAssembly.IService)"), new("TestAssembly", "TestAssembly.IServiceB", "typeof(TestAssembly.IServiceB)"), new("TestAssembly", "TestAssembly.IValidator", "typeof(TestAssembly.IValidator)"), new("TestAssembly", "TestAssembly.IValidator`1", "typeof(TestAssembly.IValidator<T>)") }),
        new(ScannerExpressionKind.Reflection, "{scrubbed}"),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 72, new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.Abstractions.TypeInfoFilter", "typeof(Specular.Abstractions.TypeInfoFilter)"), new("Specular", "Specular.Abstractions.TypeKindFilter", "typeof(Specular.Abstractions.TypeKindFilter)"), new("Specular", "Specular.ScannerExpressionKind", "") }),
        new(ScannerExpressionKind.Reflection, "{scrubbed}"),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 92, new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.SpecularProviderServiceCollectionExtensions", "typeof(Specular.SpecularProviderServiceCollectionExtensions)"), new("Specular", "Specular.SpecularScanReport", ""), new("Specular", "Specular.SpecularSupport", "typeof(Specular.SpecularSupport)"), new("TestAssembly", "TestAssembly.Nested", "typeof(TestAssembly.Nested)") }),
        new(ScannerExpressionKind.Reflection, "{scrubbed}"),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 112, new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.ServiceRegistrationAttribute`1", "typeof(Specular.ServiceRegistrationAttribute<TService>)"), new("Specular", "Specular.ServiceRegistrationAttribute`2", "typeof(Specular.ServiceRegistrationAttribute<TService1, TService2>)"), new("Specular", "Specular.ServiceRegistrationAttribute`3", "typeof(Specular.ServiceRegistrationAttribute<TService1, TService2, TService3>)"), new("Specular", "Specular.ServiceRegistrationAttribute`4", "typeof(Specular.ServiceRegistrationAttribute<TService1, TService2, TService3, TService4>)"), new("Specular", "Specular.ServiceRegistrationAttribute`5", "typeof(Specular.ServiceRegistrationAttribute<TService1, TService2, TService3, TService4, TService5>)"), new("Specular", "Specular.ServiceRegistrationAttribute`6", "typeof(Specular.ServiceRegistrationAttribute<TService1, TService2, TService3, TService4, TService5, TService6>)"), new("Specular", "Specular.ServiceRegistrationAttribute`7", "typeof(Specular.ServiceRegistrationAttribute<TService1, TService2, TService3, TService4, TService5, TService6, TService7>)"), new("Specular", "Specular.ServiceRegistrationAttribute`8", "typeof(Specular.ServiceRegistrationAttribute<TService1, TService2, TService3, TService4, TService5, TService6, TService7, TService8>)"), new("TestAssembly", "TestAssembly.IGenericService`1", "typeof(TestAssembly.IGenericService<T>)"), new("TestAssembly", "TestAssembly.IRequestHandler`2", "typeof(TestAssembly.IRequestHandler<T, R>)"), new("TestAssembly", "TestAssembly.IRequest`1", "typeof(TestAssembly.IRequest<T>)"), new("TestAssembly", "TestAssembly.IValidator`1", "typeof(TestAssembly.IValidator<T>)") }),
        new(ScannerExpressionKind.Reflection, "{scrubbed}"),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 132, new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.ScanReportAssembly", ""), new("Specular", "Specular.ScanReportType", ""), new("Specular", "Specular.ScannerExpression", ""), new("Specular", "Specular.ScannerExpressionKind", ""), new("Specular", "Specular.SpecularScanReport", ""), new("TestAssembly", "TestAssembly.GenericService", "typeof(TestAssembly.GenericService)"), new("TestAssembly", "TestAssembly.Nested+MyRecord", "typeof(TestAssembly.Nested.MyRecord)"), new("TestAssembly", "TestAssembly.Nested+Validator", "typeof(TestAssembly.Nested.Validator)"), new("TestAssembly", "TestAssembly.Request", "typeof(TestAssembly.Request)"), new("TestAssembly", "TestAssembly.RequestHandler", "typeof(TestAssembly.RequestHandler)"), new("TestAssembly", "TestAssembly.Response", "typeof(TestAssembly.Response)"), new("TestAssembly", "TestAssembly.ServiceB", "typeof(TestAssembly.ServiceB)"), new("TestProject", "Program", "typeof(Program)") }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 147, new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", "typeof(Specular.Abstractions.IReflectionAssemblySelector)"), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", "typeof(Specular.Abstractions.IReflectionTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", "typeof(Specular.Abstractions.IServiceDescriptorAssemblySelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", "typeof(Specular.Abstractions.IServiceDescriptorTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", "typeof(Specular.Abstractions.IServiceLifetimeSelector)"), new("Specular", "Specular.Abstractions.IServiceTypeSelector", "typeof(Specular.Abstractions.IServiceTypeSelector)"), new("Specular", "Specular.Abstractions.ITypeFilter", "typeof(Specular.Abstractions.ITypeFilter)"), new("Specular", "Specular.ScanReportAssembly", ""), new("Specular", "Specular.ScanReportType", ""), new("Specular", "Specular.ScannerExpression", ""), new("Specular", "Specular.SpecularProviderServiceCollectionExtensions", "typeof(Specular.SpecularProviderServiceCollectionExtensions)"), new("Specular", "Specular.SpecularScanReport", ""), new("Specular", "Specular.SpecularSupport", "typeof(Specular.SpecularSupport)"), new("TestAssembly", "TestAssembly.GenericService", "typeof(TestAssembly.GenericService)"), new("TestAssembly", "TestAssembly.GenericServiceB", "typeof(TestAssembly.GenericServiceB)"), new("TestAssembly", "TestAssembly.IGenericService`1", "typeof(TestAssembly.IGenericService<T>)"), new("TestAssembly", "TestAssembly.IOther", "typeof(TestAssembly.IOther)"), new("TestAssembly", "TestAssembly.IRequestHandler`2", "typeof(TestAssembly.IRequestHandler<T, R>)"), new("TestAssembly", "TestAssembly.IRequest`1", "typeof(TestAssembly.IRequest<T>)"), new("TestAssembly", "TestAssembly.IService", "typeof(TestAssembly.IService)"), new("TestAssembly", "TestAssembly.IServiceB", "typeof(TestAssembly.IServiceB)"), new("TestAssembly", "TestAssembly.IValidator", "typeof(TestAssembly.IValidator)"), new("TestAssembly", "TestAssembly.IValidator`1", "typeof(TestAssembly.IValidator<T>)"), new("TestAssembly", "TestAssembly.Nested", "typeof(TestAssembly.Nested)"), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", "typeof(TestAssembly.Nested.GenericServiceA)"), new("TestAssembly", "TestAssembly.Nested+MyRecord", "typeof(TestAssembly.Nested.MyRecord)"), new("TestAssembly", "TestAssembly.Nested+ServiceA", "typeof(TestAssembly.Nested.ServiceA)"), new("TestAssembly", "TestAssembly.Nested+Validator", "typeof(TestAssembly.Nested.Validator)"), new("TestAssembly", "TestAssembly.Request", "typeof(TestAssembly.Request)"), new("TestAssembly", "TestAssembly.RequestHandler", "typeof(TestAssembly.RequestHandler)"), new("TestAssembly", "TestAssembly.Response", "typeof(TestAssembly.Response)"), new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)"), new("TestAssembly", "TestAssembly.ServiceB", "typeof(TestAssembly.ServiceB)"), new("TestProject", "Program", "typeof(Program)") }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 158, new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", "typeof(Specular.Abstractions.IReflectionAssemblySelector)"), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", "typeof(Specular.Abstractions.IReflectionTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", "typeof(Specular.Abstractions.IServiceDescriptorAssemblySelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", "typeof(Specular.Abstractions.IServiceDescriptorTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", "typeof(Specular.Abstractions.IServiceLifetimeSelector)"), new("Specular", "Specular.Abstractions.IServiceTypeSelector", "typeof(Specular.Abstractions.IServiceTypeSelector)"), new("Specular", "Specular.Abstractions.ITypeFilter", "typeof(Specular.Abstractions.ITypeFilter)"), new("Specular", "Specular.SpecularProviderServiceCollectionExtensions", "typeof(Specular.SpecularProviderServiceCollectionExtensions)"), new("Specular", "Specular.SpecularScanReport", ""), new("Specular", "Specular.SpecularSupport", "typeof(Specular.SpecularSupport)"), new("TestAssembly", "TestAssembly.GenericService", "typeof(TestAssembly.GenericService)"), new("TestAssembly", "TestAssembly.GenericServiceB", "typeof(TestAssembly.GenericServiceB)"), new("TestAssembly", "TestAssembly.IGenericService`1", "typeof(TestAssembly.IGenericService<T>)"), new("TestAssembly", "TestAssembly.IOther", "typeof(TestAssembly.IOther)"), new("TestAssembly", "TestAssembly.IRequestHandler`2", "typeof(TestAssembly.IRequestHandler<T, R>)"), new("TestAssembly", "TestAssembly.IRequest`1", "typeof(TestAssembly.IRequest<T>)"), new("TestAssembly", "TestAssembly.IService", "typeof(TestAssembly.IService)"), new("TestAssembly", "TestAssembly.IServiceB", "typeof(TestAssembly.IServiceB)"), new("TestAssembly", "TestAssembly.IValidator", "typeof(TestAssembly.IValidator)"), new("TestAssembly", "TestAssembly.IValidator`1", "typeof(TestAssembly.IValidator<T>)"), new("TestAssembly", "TestAssembly.Nested", "typeof(TestAssembly.Nested)"), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", "typeof(TestAssembly.Nested.GenericServiceA)"), new("TestAssembly", "TestAssembly.Nested+MyRecord", "typeof(TestAssembly.Nested.MyRecord)"), new("TestAssembly", "TestAssembly.Nested+ServiceA", "typeof(TestAssembly.Nested.ServiceA)"), new("TestAssembly", "TestAssembly.Nested+Validator", "typeof(TestAssembly.Nested.Validator)"), new("TestAssembly", "TestAssembly.Request", "typeof(TestAssembly.Request)"), new("TestAssembly", "TestAssembly.RequestHandler", "typeof(TestAssembly.RequestHandler)"), new("TestAssembly", "TestAssembly.Response", "typeof(TestAssembly.Response)"), new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)"), new("TestAssembly", "TestAssembly.ServiceB", "typeof(TestAssembly.ServiceB)"), new("TestProject", "Program", "typeof(Program)") }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 169, new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", "typeof(Specular.Abstractions.IReflectionAssemblySelector)"), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", "typeof(Specular.Abstractions.IReflectionTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", "typeof(Specular.Abstractions.IServiceDescriptorAssemblySelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", "typeof(Specular.Abstractions.IServiceDescriptorTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", "typeof(Specular.Abstractions.IServiceLifetimeSelector)"), new("Specular", "Specular.Abstractions.IServiceTypeSelector", "typeof(Specular.Abstractions.IServiceTypeSelector)"), new("Specular", "Specular.Abstractions.ITypeFilter", "typeof(Specular.Abstractions.ITypeFilter)"), new("Specular", "Specular.Abstractions.TypeInfoFilter", "typeof(Specular.Abstractions.TypeInfoFilter)"), new("Specular", "Specular.Abstractions.TypeKindFilter", "typeof(Specular.Abstractions.TypeKindFilter)"), new("Specular", "Specular.ScanReportAssembly", ""), new("Specular", "Specular.ScanReportType", ""), new("Specular", "Specular.ScannerExpression", ""), new("Specular", "Specular.ScannerExpressionKind", ""), new("Specular", "Specular.SpecularProviderServiceCollectionExtensions", "typeof(Specular.SpecularProviderServiceCollectionExtensions)"), new("Specular", "Specular.SpecularScanReport", ""), new("Specular", "Specular.SpecularSupport", "typeof(Specular.SpecularSupport)"), new("TestAssembly", "TestAssembly.GenericService", "typeof(TestAssembly.GenericService)"), new("TestAssembly", "TestAssembly.GenericServiceB", "typeof(TestAssembly.GenericServiceB)"), new("TestAssembly", "TestAssembly.IOther", "typeof(TestAssembly.IOther)"), new("TestAssembly", "TestAssembly.IService", "typeof(TestAssembly.IService)"), new("TestAssembly", "TestAssembly.IServiceB", "typeof(TestAssembly.IServiceB)"), new("TestAssembly", "TestAssembly.IValidator", "typeof(TestAssembly.IValidator)"), new("TestAssembly", "TestAssembly.Nested", "typeof(TestAssembly.Nested)"), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", "typeof(TestAssembly.Nested.GenericServiceA)"), new("TestAssembly", "TestAssembly.Nested+MyRecord", "typeof(TestAssembly.Nested.MyRecord)"), new("TestAssembly", "TestAssembly.Nested+ServiceA", "typeof(TestAssembly.Nested.ServiceA)"), new("TestAssembly", "TestAssembly.Nested+Validator", "typeof(TestAssembly.Nested.Validator)"), new("TestAssembly", "TestAssembly.Request", "typeof(TestAssembly.Request)"), new("TestAssembly", "TestAssembly.RequestHandler", "typeof(TestAssembly.RequestHandler)"), new("TestAssembly", "TestAssembly.Response", "typeof(TestAssembly.Response)"), new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)"), new("TestAssembly", "TestAssembly.ServiceB", "typeof(TestAssembly.ServiceB)"), new("TestProject", "Program", "typeof(Program)") }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 180, new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.SpecularSupport", "typeof(Specular.SpecularSupport)") }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 190, new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.SpecularSupport", "typeof(Specular.SpecularSupport)") }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 200, new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", "typeof(Specular.Abstractions.IReflectionAssemblySelector)"), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", "typeof(Specular.Abstractions.IReflectionTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", "typeof(Specular.Abstractions.IServiceDescriptorAssemblySelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", "typeof(Specular.Abstractions.IServiceDescriptorTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", "typeof(Specular.Abstractions.IServiceLifetimeSelector)"), new("Specular", "Specular.Abstractions.IServiceTypeSelector", "typeof(Specular.Abstractions.IServiceTypeSelector)"), new("Specular", "Specular.Abstractions.ITypeFilter", "typeof(Specular.Abstractions.ITypeFilter)"), new("Specular", "Specular.Abstractions.TypeInfoFilter", "typeof(Specular.Abstractions.TypeInfoFilter)"), new("Specular", "Specular.Abstractions.TypeKindFilter", "typeof(Specular.Abstractions.TypeKindFilter)"), new("Specular", "Specular.ScanReportAssembly", ""), new("Specular", "Specular.ScanReportType", ""), new("Specular", "Specular.ScannerExpression", ""), new("Specular", "Specular.ScannerExpressionKind", ""), new("Specular", "Specular.SpecularProviderServiceCollectionExtensions", "typeof(Specular.SpecularProviderServiceCollectionExtensions)"), new("Specular", "Specular.SpecularScanReport", ""), new("TestAssembly", "TestAssembly.GenericService", "typeof(TestAssembly.GenericService)"), new("TestAssembly", "TestAssembly.GenericServiceB", "typeof(TestAssembly.GenericServiceB)"), new("TestAssembly", "TestAssembly.IGenericService`1", "typeof(TestAssembly.IGenericService<T>)"), new("TestAssembly", "TestAssembly.IOther", "typeof(TestAssembly.IOther)"), new("TestAssembly", "TestAssembly.IRequestHandler`2", "typeof(TestAssembly.IRequestHandler<T, R>)"), new("TestAssembly", "TestAssembly.IRequest`1", "typeof(TestAssembly.IRequest<T>)"), new("TestAssembly", "TestAssembly.IService", "typeof(TestAssembly.IService)"), new("TestAssembly", "TestAssembly.IServiceB", "typeof(TestAssembly.IServiceB)"), new("TestAssembly", "TestAssembly.IValidator", "typeof(TestAssembly.IValidator)"), new("TestAssembly", "TestAssembly.IValidator`1", "typeof(TestAssembly.IValidator<T>)"), new("TestAssembly", "TestAssembly.Nested", "typeof(TestAssembly.Nested)"), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", "typeof(TestAssembly.Nested.GenericServiceA)"), new("TestAssembly", "TestAssembly.Nested+MyRecord", "typeof(TestAssembly.Nested.MyRecord)"), new("TestAssembly", "TestAssembly.Nested+ServiceA", "typeof(TestAssembly.Nested.ServiceA)"), new("TestAssembly", "TestAssembly.Nested+Validator", "typeof(TestAssembly.Nested.Validator)"), new("TestAssembly", "TestAssembly.Request", "typeof(TestAssembly.Request)"), new("TestAssembly", "TestAssembly.RequestHandler", "typeof(TestAssembly.RequestHandler)"), new("TestAssembly", "TestAssembly.Response", "typeof(TestAssembly.Response)"), new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)"), new("TestAssembly", "TestAssembly.ServiceB", "typeof(TestAssembly.ServiceB)"), new("TestProject", "Program", "typeof(Program)") }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 211, new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", "typeof(Specular.Abstractions.IReflectionAssemblySelector)"), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", "typeof(Specular.Abstractions.IReflectionTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", "typeof(Specular.Abstractions.IServiceDescriptorAssemblySelector)"), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", "typeof(Specular.Abstractions.IServiceDescriptorTypeSelector)"), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", "typeof(Specular.Abstractions.IServiceLifetimeSelector)"), new("Specular", "Specular.Abstractions.IServiceTypeSelector", "typeof(Specular.Abstractions.IServiceTypeSelector)"), new("Specular", "Specular.Abstractions.ITypeFilter", "typeof(Specular.Abstractions.ITypeFilter)"), new("Specular", "Specular.Abstractions.TypeInfoFilter", "typeof(Specular.Abstractions.TypeInfoFilter)"), new("Specular", "Specular.Abstractions.TypeKindFilter", "typeof(Specular.Abstractions.TypeKindFilter)"), new("Specular", "Specular.ScanReportAssembly", ""), new("Specular", "Specular.ScanReportType", ""), new("Specular", "Specular.ScannerExpression", ""), new("Specular", "Specular.ScannerExpressionKind", ""), new("Specular", "Specular.SpecularProviderServiceCollectionExtensions", "typeof(Specular.SpecularProviderServiceCollectionExtensions)"), new("Specular", "Specular.SpecularScanReport", ""), new("TestAssembly", "TestAssembly.GenericService", "typeof(TestAssembly.GenericService)"), new("TestAssembly", "TestAssembly.GenericServiceB", "typeof(TestAssembly.GenericServiceB)"), new("TestAssembly", "TestAssembly.IGenericService`1", "typeof(TestAssembly.IGenericService<T>)"), new("TestAssembly", "TestAssembly.IOther", "typeof(TestAssembly.IOther)"), new("TestAssembly", "TestAssembly.IRequestHandler`2", "typeof(TestAssembly.IRequestHandler<T, R>)"), new("TestAssembly", "TestAssembly.IRequest`1", "typeof(TestAssembly.IRequest<T>)"), new("TestAssembly", "TestAssembly.IService", "typeof(TestAssembly.IService)"), new("TestAssembly", "TestAssembly.IServiceB", "typeof(TestAssembly.IServiceB)"), new("TestAssembly", "TestAssembly.IValidator", "typeof(TestAssembly.IValidator)"), new("TestAssembly", "TestAssembly.IValidator`1", "typeof(TestAssembly.IValidator<T>)"), new("TestAssembly", "TestAssembly.Nested", "typeof(TestAssembly.Nested)"), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", "typeof(TestAssembly.Nested.GenericServiceA)"), new("TestAssembly", "TestAssembly.Nested+MyRecord", "typeof(TestAssembly.Nested.MyRecord)"), new("TestAssembly", "TestAssembly.Nested+ServiceA", "typeof(TestAssembly.Nested.ServiceA)"), new("TestAssembly", "TestAssembly.Nested+Validator", "typeof(TestAssembly.Nested.Validator)"), new("TestAssembly", "TestAssembly.Request", "typeof(TestAssembly.Request)"), new("TestAssembly", "TestAssembly.RequestHandler", "typeof(TestAssembly.RequestHandler)"), new("TestAssembly", "TestAssembly.Response", "typeof(TestAssembly.Response)"), new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)"), new("TestAssembly", "TestAssembly.ServiceB", "typeof(TestAssembly.ServiceB)"), new("TestProject", "Program", "typeof(Program)") }),
        new(ScannerExpressionKind.Reflection, "{scrubbed}"),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 262, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 268, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+ServiceA", "typeof(TestAssembly.Nested.ServiceA)"), new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)"), new("TestAssembly", "TestAssembly.ServiceB", "typeof(TestAssembly.ServiceB)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 274, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+ServiceA", "typeof(TestAssembly.Nested.ServiceA)"), new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)"), new("TestAssembly", "TestAssembly.ServiceB", "typeof(TestAssembly.ServiceB)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 279, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+ServiceA", "typeof(TestAssembly.Nested.ServiceA)"), new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)"), new("TestAssembly", "TestAssembly.ServiceB", "typeof(TestAssembly.ServiceB)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 285, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+ServiceA", "typeof(TestAssembly.Nested.ServiceA)"), new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)"), new("TestAssembly", "TestAssembly.ServiceB", "typeof(TestAssembly.ServiceB)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 291, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.GenericService", "typeof(TestAssembly.GenericService)"), new("TestAssembly", "TestAssembly.GenericServiceB", "typeof(TestAssembly.GenericServiceB)"), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", "typeof(TestAssembly.Nested.GenericServiceA)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 296, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.GenericService", "typeof(TestAssembly.GenericService)"), new("TestAssembly", "TestAssembly.GenericServiceB", "typeof(TestAssembly.GenericServiceB)"), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", "typeof(TestAssembly.Nested.GenericServiceA)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 302, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.RequestHandler", "typeof(TestAssembly.RequestHandler)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 307, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 313, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+ServiceA", "typeof(TestAssembly.Nested.ServiceA)"), new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)"), new("TestAssembly", "TestAssembly.ServiceB", "typeof(TestAssembly.ServiceB)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 319, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+ServiceA", "typeof(TestAssembly.Nested.ServiceA)"), new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)"), new("TestAssembly", "TestAssembly.ServiceB", "typeof(TestAssembly.ServiceB)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 325, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.GenericService", "typeof(TestAssembly.GenericService)"), new("TestAssembly", "TestAssembly.GenericServiceB", "typeof(TestAssembly.GenericServiceB)"), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", "typeof(TestAssembly.Nested.GenericServiceA)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 331, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+Validator", "typeof(TestAssembly.Nested.Validator)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 336, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+ServiceA", "typeof(TestAssembly.Nested.ServiceA)"), new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)"), new("TestAssembly", "TestAssembly.ServiceB", "typeof(TestAssembly.ServiceB)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 341, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.GenericService", "typeof(TestAssembly.GenericService)"), new("TestAssembly", "TestAssembly.GenericServiceB", "typeof(TestAssembly.GenericServiceB)"), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", "typeof(TestAssembly.Nested.GenericServiceA)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 347, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.GenericService", "typeof(TestAssembly.GenericService)"), new("TestAssembly", "TestAssembly.GenericServiceB", "typeof(TestAssembly.GenericServiceB)"), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", "typeof(TestAssembly.Nested.GenericServiceA)") }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 366, new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.GenericService", "typeof(TestAssembly.GenericService)"), new("TestAssembly", "TestAssembly.GenericServiceB", "typeof(TestAssembly.GenericServiceB)"), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", "typeof(TestAssembly.Nested.GenericServiceA)"), new("TestAssembly", "TestAssembly.Nested+MyRecord", "typeof(TestAssembly.Nested.MyRecord)"), new("TestAssembly", "TestAssembly.Nested+ServiceA", "typeof(TestAssembly.Nested.ServiceA)"), new("TestAssembly", "TestAssembly.Nested+Validator", "typeof(TestAssembly.Nested.Validator)"), new("TestAssembly", "TestAssembly.Request", "typeof(TestAssembly.Request)"), new("TestAssembly", "TestAssembly.RequestHandler", "typeof(TestAssembly.RequestHandler)"), new("TestAssembly", "TestAssembly.Response", "typeof(TestAssembly.Response)"), new("TestAssembly", "TestAssembly.Service", "typeof(TestAssembly.Service)"), new("TestAssembly", "TestAssembly.ServiceB", "typeof(TestAssembly.ServiceB)") }),
    };

    public const string MermaidDiagram = @"flowchart TD
    F0[Input0.cs:16] --> E0{Assembly}
    E0 --> E0A0[Specular]
    E0 --> E0A1[System.ComponentModel]
    E0 --> E0A2[TestAssembly]
    E0 --> E0A3[TestProject]
    F1[Input0.cs:17] --> E1{Assembly}
    E1 --> E1A0[Specular]
    E1 --> E1A1[System.ComponentModel]
    E1 --> E1A2[TestAssembly]
    E1 --> E1A3[TestProject]
    F2[Input0.cs:18] --> E2{Assembly}
    E2 --> E2A0[Specular]
    E2 --> E2A1[System.ComponentModel]
    E2 --> E2A2[TestAssembly]
    E2 --> E2A3[TestProject]
    F3[Input0.cs:20] --> E3{Assembly}
    E3 --> E3A0[TestProject]
    F4[Input0.cs:21] --> E4{Assembly}
    E4 --> E4A0[TestProject]
    F5[Input0.cs:22] --> E5{Reflection}
    E5 --> E5T0[Specular.Abstractions.IReflectionAssemblySelector]
    E5 --> E5T1[Specular.Abstractions.IReflectionTypeSelector]
    E5 --> E5T2[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E5 --> E5T3[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E5 --> E5T4[Specular.Abstractions.IServiceLifetimeSelector]
    E5 --> E5T5[Specular.Abstractions.IServiceTypeSelector]
    E5 --> E5T6[Specular.Abstractions.ITypeFilter]
    E5 --> E5T7[Specular.Abstractions.TypeInfoFilter]
    E5 --> E5T8[Specular.Abstractions.TypeKindFilter]
    E5 --> E5T9[Specular.ScannerExpressionKind]
    E5 --> E5T10[TestAssembly.IGenericService`1]
    E5 --> E5T11[TestAssembly.IOther]
    E5 --> E5T12[TestAssembly.IRequestHandler`2]
    E5 --> E5T13[TestAssembly.IRequest`1]
    E5 --> E5T14[TestAssembly.IService]
    E5 --> E5T15[TestAssembly.IServiceB]
    E5 --> E5T16[TestAssembly.IValidator]
    E5 --> E5T17[TestAssembly.IValidator`1]
    F6[Input0.cs:32] --> E6{Reflection}
    E6 --> E6T0[Specular.Abstractions.IReflectionAssemblySelector]
    E6 --> E6T1[Specular.Abstractions.IReflectionTypeSelector]
    E6 --> E6T2[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E6 --> E6T3[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E6 --> E6T4[Specular.Abstractions.IServiceLifetimeSelector]
    E6 --> E6T5[Specular.Abstractions.IServiceTypeSelector]
    E6 --> E6T6[Specular.Abstractions.ITypeFilter]
    E6 --> E6T7[TestAssembly.IGenericService`1]
    E6 --> E6T8[TestAssembly.IOther]
    E6 --> E6T9[TestAssembly.IRequestHandler`2]
    E6 --> E6T10[TestAssembly.IRequest`1]
    E6 --> E6T11[TestAssembly.IService]
    E6 --> E6T12[TestAssembly.IServiceB]
    E6 --> E6T13[TestAssembly.IValidator]
    E6 --> E6T14[TestAssembly.IValidator`1]
    F7[Input0.cs:42] --> E7{Reflection}
    E7 --> E7T0[Microsoft.CodeAnalysis.EmbeddedAttribute]
    E7 --> E7T1[Specular.Abstractions.ExcludeFromSpecularAttribute]
    E7 --> E7T2[Specular.Abstractions.SpecularHashAttribute]
    E7 --> E7T3[Specular.Abstractions.TypeInfoFilter]
    E7 --> E7T4[Specular.Abstractions.TypeKindFilter]
    E7 --> E7T5[Specular.RegistrationLifetimeAttribute]
    E7 --> E7T6[Specular.ScanReportAssembly]
    E7 --> E7T7[Specular.ScanReportType]
    E7 --> E7T8[Specular.ScannerExpression]
    E7 --> E7T9[Specular.ScannerExpressionKind]
    E7 --> E7T10[Specular.ServiceRegistrationAttribute]
    E7 --> E7T11[Specular.ServiceRegistrationAttribute`1]
    E7 --> E7T12[Specular.ServiceRegistrationAttribute`2]
    E7 --> E7T13[Specular.ServiceRegistrationAttribute`3]
    E7 --> E7T14[Specular.ServiceRegistrationAttribute`4]
    E7 --> E7T15[Specular.ServiceRegistrationAttribute`5]
    E7 --> E7T16[Specular.ServiceRegistrationAttribute`6]
    E7 --> E7T17[Specular.ServiceRegistrationAttribute`7]
    E7 --> E7T18[Specular.ServiceRegistrationAttribute`8]
    E7 --> E7T19[Specular.SpecularProviderServiceCollectionExtensions]
    E7 --> E7T20[Specular.SpecularScanReport]
    E7 --> E7T21[Specular.SpecularSupport]
    E7 --> E7T22[Microsoft.CodeAnalysis.EmbeddedAttribute]
    E7 --> E7T23[TestAssembly.GenericService]
    E7 --> E7T24[TestAssembly.GenericServiceB]
    E7 --> E7T25[TestAssembly.Nested]
    E7 --> E7T26[TestAssembly.Nested+GenericServiceA]
    E7 --> E7T27[TestAssembly.Nested+MyRecord]
    E7 --> E7T28[TestAssembly.Nested+ServiceA]
    E7 --> E7T29[TestAssembly.Nested+Validator]
    E7 --> E7T30[TestAssembly.Request]
    E7 --> E7T31[TestAssembly.RequestHandler]
    E7 --> E7T32[TestAssembly.Response]
    E7 --> E7T33[TestAssembly.Service]
    E7 --> E7T34[TestAssembly.ServiceB]
    E7 --> E7T35[Microsoft.CodeAnalysis.EmbeddedAttribute]
    E7 --> E7T36[Program]
    F8[Input0.cs:52] --> E8{Reflection}
    E8 --> E8T0[Specular.Abstractions.IReflectionAssemblySelector]
    E8 --> E8T1[Specular.Abstractions.IReflectionTypeSelector]
    E8 --> E8T2[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E8 --> E8T3[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E8 --> E8T4[Specular.Abstractions.IServiceLifetimeSelector]
    E8 --> E8T5[Specular.Abstractions.IServiceTypeSelector]
    E8 --> E8T6[Specular.Abstractions.ITypeFilter]
    E8 --> E8T7[TestAssembly.IGenericService`1]
    E8 --> E8T8[TestAssembly.IOther]
    E8 --> E8T9[TestAssembly.IRequestHandler`2]
    E8 --> E8T10[TestAssembly.IRequest`1]
    E8 --> E8T11[TestAssembly.IService]
    E8 --> E8T12[TestAssembly.IServiceB]
    E8 --> E8T13[TestAssembly.IValidator]
    E8 --> E8T14[TestAssembly.IValidator`1]
    F9[Input0.cs:62] --> E9{Reflection}
    E9 --> E9T0[Specular.Abstractions.ExcludeFromSpecularAttribute]
    E9 --> E9T1[Specular.Abstractions.IReflectionAssemblySelector]
    E9 --> E9T2[Specular.Abstractions.IReflectionTypeSelector]
    E9 --> E9T3[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E9 --> E9T4[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E9 --> E9T5[Specular.Abstractions.IServiceLifetimeSelector]
    E9 --> E9T6[Specular.Abstractions.IServiceTypeSelector]
    E9 --> E9T7[Specular.Abstractions.ITypeFilter]
    E9 --> E9T8[Specular.Abstractions.SpecularHashAttribute]
    E9 --> E9T9[Specular.Abstractions.TypeInfoFilter]
    E9 --> E9T10[Specular.Abstractions.TypeKindFilter]
    E9 --> E9T11[Specular.RegistrationLifetimeAttribute]
    E9 --> E9T12[Specular.ServiceRegistrationAttribute]
    E9 --> E9T13[Specular.ServiceRegistrationAttribute`1]
    E9 --> E9T14[Specular.ServiceRegistrationAttribute`2]
    E9 --> E9T15[Specular.ServiceRegistrationAttribute`3]
    E9 --> E9T16[Specular.ServiceRegistrationAttribute`4]
    E9 --> E9T17[Specular.ServiceRegistrationAttribute`5]
    E9 --> E9T18[Specular.ServiceRegistrationAttribute`6]
    E9 --> E9T19[Specular.ServiceRegistrationAttribute`7]
    E9 --> E9T20[Specular.ServiceRegistrationAttribute`8]
    E9 --> E9T21[Specular.SpecularProviderServiceCollectionExtensions]
    E9 --> E9T22[Specular.SpecularSupport]
    E9 --> E9T23[TestAssembly.GenericServiceB]
    E9 --> E9T24[TestAssembly.IGenericService`1]
    E9 --> E9T25[TestAssembly.IOther]
    E9 --> E9T26[TestAssembly.IRequestHandler`2]
    E9 --> E9T27[TestAssembly.IRequest`1]
    E9 --> E9T28[TestAssembly.IService]
    E9 --> E9T29[TestAssembly.IServiceB]
    E9 --> E9T30[TestAssembly.IValidator]
    E9 --> E9T31[TestAssembly.IValidator`1]
    E9 --> E9T32[TestAssembly.Nested]
    E9 --> E9T33[TestAssembly.Nested+GenericServiceA]
    E9 --> E9T34[TestAssembly.Nested+ServiceA]
    E9 --> E9T35[TestAssembly.Service]
    F10[Input0.cs:72] --> E10{Reflection}
    E10 --> E10T0[Specular.Abstractions.TypeInfoFilter]
    E10 --> E10T1[Specular.Abstractions.TypeKindFilter]
    E10 --> E10T2[Specular.ScannerExpressionKind]
    F11[Input0.cs:82] --> E11{Reflection}
    E11 --> E11T0[Microsoft.CodeAnalysis.EmbeddedAttribute]
    E11 --> E11T1[Specular.Abstractions.SpecularHashAttribute]
    E11 --> E11T2[Specular.Abstractions.TypeInfoFilter]
    E11 --> E11T3[Specular.Abstractions.TypeKindFilter]
    E11 --> E11T4[Specular.ScanReportAssembly]
    E11 --> E11T5[Specular.ScanReportType]
    E11 --> E11T6[Specular.ScannerExpression]
    E11 --> E11T7[Specular.ScannerExpressionKind]
    E11 --> E11T8[Specular.ServiceRegistrationAttribute`1]
    E11 --> E11T9[Specular.ServiceRegistrationAttribute`2]
    E11 --> E11T10[Specular.ServiceRegistrationAttribute`3]
    E11 --> E11T11[Specular.ServiceRegistrationAttribute`4]
    E11 --> E11T12[Specular.ServiceRegistrationAttribute`5]
    E11 --> E11T13[Specular.ServiceRegistrationAttribute`6]
    E11 --> E11T14[Specular.ServiceRegistrationAttribute`7]
    E11 --> E11T15[Specular.ServiceRegistrationAttribute`8]
    E11 --> E11T16[Microsoft.CodeAnalysis.EmbeddedAttribute]
    E11 --> E11T17[Microsoft.CodeAnalysis.EmbeddedAttribute]
    F12[Input0.cs:92] --> E12{Reflection}
    E12 --> E12T0[Specular.SpecularProviderServiceCollectionExtensions]
    E12 --> E12T1[Specular.SpecularScanReport]
    E12 --> E12T2[Specular.SpecularSupport]
    E12 --> E12T3[TestAssembly.Nested]
    F13[Input0.cs:102] --> E13{Reflection}
    E13 --> E13T0[Microsoft.CodeAnalysis.EmbeddedAttribute]
    E13 --> E13T1[Specular.Abstractions.ExcludeFromSpecularAttribute]
    E13 --> E13T2[Specular.Abstractions.IReflectionAssemblySelector]
    E13 --> E13T3[Specular.Abstractions.IReflectionTypeSelector]
    E13 --> E13T4[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E13 --> E13T5[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E13 --> E13T6[Specular.Abstractions.IServiceLifetimeSelector]
    E13 --> E13T7[Specular.Abstractions.IServiceTypeSelector]
    E13 --> E13T8[Specular.Abstractions.ITypeFilter]
    E13 --> E13T9[Specular.Abstractions.SpecularHashAttribute]
    E13 --> E13T10[Specular.Abstractions.TypeInfoFilter]
    E13 --> E13T11[Specular.Abstractions.TypeKindFilter]
    E13 --> E13T12[Specular.RegistrationLifetimeAttribute]
    E13 --> E13T13[Specular.ScanReportAssembly]
    E13 --> E13T14[Specular.ScanReportType]
    E13 --> E13T15[Specular.ScannerExpression]
    E13 --> E13T16[Specular.ScannerExpressionKind]
    E13 --> E13T17[Specular.ServiceRegistrationAttribute]
    E13 --> E13T18[Specular.ServiceRegistrationAttribute`1]
    E13 --> E13T19[Specular.ServiceRegistrationAttribute`2]
    E13 --> E13T20[Specular.ServiceRegistrationAttribute`3]
    E13 --> E13T21[Specular.ServiceRegistrationAttribute`4]
    E13 --> E13T22[Specular.ServiceRegistrationAttribute`5]
    E13 --> E13T23[Specular.ServiceRegistrationAttribute`6]
    E13 --> E13T24[Specular.ServiceRegistrationAttribute`7]
    E13 --> E13T25[Specular.ServiceRegistrationAttribute`8]
    E13 --> E13T26[Microsoft.CodeAnalysis.EmbeddedAttribute]
    E13 --> E13T27[TestAssembly.GenericService]
    E13 --> E13T28[TestAssembly.GenericServiceB]
    E13 --> E13T29[TestAssembly.IGenericService`1]
    E13 --> E13T30[TestAssembly.IOther]
    E13 --> E13T31[TestAssembly.IRequestHandler`2]
    E13 --> E13T32[TestAssembly.IRequest`1]
    E13 --> E13T33[TestAssembly.IService]
    E13 --> E13T34[TestAssembly.IServiceB]
    E13 --> E13T35[TestAssembly.IValidator]
    E13 --> E13T36[TestAssembly.IValidator`1]
    E13 --> E13T37[TestAssembly.Nested+GenericServiceA]
    E13 --> E13T38[TestAssembly.Nested+MyRecord]
    E13 --> E13T39[TestAssembly.Nested+ServiceA]
    E13 --> E13T40[TestAssembly.Nested+Validator]
    E13 --> E13T41[TestAssembly.Request]
    E13 --> E13T42[TestAssembly.RequestHandler]
    E13 --> E13T43[TestAssembly.Response]
    E13 --> E13T44[TestAssembly.Service]
    E13 --> E13T45[TestAssembly.ServiceB]
    E13 --> E13T46[Microsoft.CodeAnalysis.EmbeddedAttribute]
    E13 --> E13T47[Program]
    F14[Input0.cs:112] --> E14{Reflection}
    E14 --> E14T0[Specular.ServiceRegistrationAttribute`1]
    E14 --> E14T1[Specular.ServiceRegistrationAttribute`2]
    E14 --> E14T2[Specular.ServiceRegistrationAttribute`3]
    E14 --> E14T3[Specular.ServiceRegistrationAttribute`4]
    E14 --> E14T4[Specular.ServiceRegistrationAttribute`5]
    E14 --> E14T5[Specular.ServiceRegistrationAttribute`6]
    E14 --> E14T6[Specular.ServiceRegistrationAttribute`7]
    E14 --> E14T7[Specular.ServiceRegistrationAttribute`8]
    E14 --> E14T8[TestAssembly.IGenericService`1]
    E14 --> E14T9[TestAssembly.IRequestHandler`2]
    E14 --> E14T10[TestAssembly.IRequest`1]
    E14 --> E14T11[TestAssembly.IValidator`1]
    F15[Input0.cs:122] --> E15{Reflection}
    E15 --> E15T0[Microsoft.CodeAnalysis.EmbeddedAttribute]
    E15 --> E15T1[Specular.Abstractions.ExcludeFromSpecularAttribute]
    E15 --> E15T2[Specular.Abstractions.SpecularHashAttribute]
    E15 --> E15T3[Specular.Abstractions.TypeInfoFilter]
    E15 --> E15T4[Specular.Abstractions.TypeKindFilter]
    E15 --> E15T5[Specular.RegistrationLifetimeAttribute]
    E15 --> E15T6[Specular.ScanReportAssembly]
    E15 --> E15T7[Specular.ScanReportType]
    E15 --> E15T8[Specular.ScannerExpression]
    E15 --> E15T9[Specular.ScannerExpressionKind]
    E15 --> E15T10[Specular.ServiceRegistrationAttribute]
    E15 --> E15T11[Specular.ServiceRegistrationAttribute`1]
    E15 --> E15T12[Specular.ServiceRegistrationAttribute`2]
    E15 --> E15T13[Specular.ServiceRegistrationAttribute`3]
    E15 --> E15T14[Specular.ServiceRegistrationAttribute`4]
    E15 --> E15T15[Specular.ServiceRegistrationAttribute`5]
    E15 --> E15T16[Specular.ServiceRegistrationAttribute`6]
    E15 --> E15T17[Specular.ServiceRegistrationAttribute`7]
    E15 --> E15T18[Specular.ServiceRegistrationAttribute`8]
    E15 --> E15T19[Specular.SpecularProviderServiceCollectionExtensions]
    E15 --> E15T20[Specular.SpecularScanReport]
    E15 --> E15T21[Specular.SpecularSupport]
    E15 --> E15T22[Microsoft.CodeAnalysis.EmbeddedAttribute]
    E15 --> E15T23[TestAssembly.GenericService]
    E15 --> E15T24[TestAssembly.GenericServiceB]
    E15 --> E15T25[TestAssembly.Nested]
    E15 --> E15T26[TestAssembly.Nested+GenericServiceA]
    E15 --> E15T27[TestAssembly.Nested+MyRecord]
    E15 --> E15T28[TestAssembly.Nested+ServiceA]
    E15 --> E15T29[TestAssembly.Nested+Validator]
    E15 --> E15T30[TestAssembly.Request]
    E15 --> E15T31[TestAssembly.RequestHandler]
    E15 --> E15T32[TestAssembly.Response]
    E15 --> E15T33[TestAssembly.Service]
    E15 --> E15T34[TestAssembly.ServiceB]
    E15 --> E15T35[Microsoft.CodeAnalysis.EmbeddedAttribute]
    E15 --> E15T36[Program]
    F16[Input0.cs:132] --> E16{Reflection}
    E16 --> E16T0[Specular.ScanReportAssembly]
    E16 --> E16T1[Specular.ScanReportType]
    E16 --> E16T2[Specular.ScannerExpression]
    E16 --> E16T3[Specular.ScannerExpressionKind]
    E16 --> E16T4[Specular.SpecularScanReport]
    E16 --> E16T5[TestAssembly.GenericService]
    E16 --> E16T6[TestAssembly.Nested+MyRecord]
    E16 --> E16T7[TestAssembly.Nested+Validator]
    E16 --> E16T8[TestAssembly.Request]
    E16 --> E16T9[TestAssembly.RequestHandler]
    E16 --> E16T10[TestAssembly.Response]
    E16 --> E16T11[TestAssembly.ServiceB]
    E16 --> E16T12[Program]
    F17[Input0.cs:147] --> E17{Reflection}
    E17 --> E17T0[Specular.Abstractions.IReflectionAssemblySelector]
    E17 --> E17T1[Specular.Abstractions.IReflectionTypeSelector]
    E17 --> E17T2[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E17 --> E17T3[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E17 --> E17T4[Specular.Abstractions.IServiceLifetimeSelector]
    E17 --> E17T5[Specular.Abstractions.IServiceTypeSelector]
    E17 --> E17T6[Specular.Abstractions.ITypeFilter]
    E17 --> E17T7[Specular.ScanReportAssembly]
    E17 --> E17T8[Specular.ScanReportType]
    E17 --> E17T9[Specular.ScannerExpression]
    E17 --> E17T10[Specular.SpecularProviderServiceCollectionExtensions]
    E17 --> E17T11[Specular.SpecularScanReport]
    E17 --> E17T12[Specular.SpecularSupport]
    E17 --> E17T13[TestAssembly.GenericService]
    E17 --> E17T14[TestAssembly.GenericServiceB]
    E17 --> E17T15[TestAssembly.IGenericService`1]
    E17 --> E17T16[TestAssembly.IOther]
    E17 --> E17T17[TestAssembly.IRequestHandler`2]
    E17 --> E17T18[TestAssembly.IRequest`1]
    E17 --> E17T19[TestAssembly.IService]
    E17 --> E17T20[TestAssembly.IServiceB]
    E17 --> E17T21[TestAssembly.IValidator]
    E17 --> E17T22[TestAssembly.IValidator`1]
    E17 --> E17T23[TestAssembly.Nested]
    E17 --> E17T24[TestAssembly.Nested+GenericServiceA]
    E17 --> E17T25[TestAssembly.Nested+MyRecord]
    E17 --> E17T26[TestAssembly.Nested+ServiceA]
    E17 --> E17T27[TestAssembly.Nested+Validator]
    E17 --> E17T28[TestAssembly.Request]
    E17 --> E17T29[TestAssembly.RequestHandler]
    E17 --> E17T30[TestAssembly.Response]
    E17 --> E17T31[TestAssembly.Service]
    E17 --> E17T32[TestAssembly.ServiceB]
    E17 --> E17T33[Program]
    F18[Input0.cs:158] --> E18{Reflection}
    E18 --> E18T0[Specular.Abstractions.IReflectionAssemblySelector]
    E18 --> E18T1[Specular.Abstractions.IReflectionTypeSelector]
    E18 --> E18T2[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E18 --> E18T3[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E18 --> E18T4[Specular.Abstractions.IServiceLifetimeSelector]
    E18 --> E18T5[Specular.Abstractions.IServiceTypeSelector]
    E18 --> E18T6[Specular.Abstractions.ITypeFilter]
    E18 --> E18T7[Specular.SpecularProviderServiceCollectionExtensions]
    E18 --> E18T8[Specular.SpecularScanReport]
    E18 --> E18T9[Specular.SpecularSupport]
    E18 --> E18T10[TestAssembly.GenericService]
    E18 --> E18T11[TestAssembly.GenericServiceB]
    E18 --> E18T12[TestAssembly.IGenericService`1]
    E18 --> E18T13[TestAssembly.IOther]
    E18 --> E18T14[TestAssembly.IRequestHandler`2]
    E18 --> E18T15[TestAssembly.IRequest`1]
    E18 --> E18T16[TestAssembly.IService]
    E18 --> E18T17[TestAssembly.IServiceB]
    E18 --> E18T18[TestAssembly.IValidator]
    E18 --> E18T19[TestAssembly.IValidator`1]
    E18 --> E18T20[TestAssembly.Nested]
    E18 --> E18T21[TestAssembly.Nested+GenericServiceA]
    E18 --> E18T22[TestAssembly.Nested+MyRecord]
    E18 --> E18T23[TestAssembly.Nested+ServiceA]
    E18 --> E18T24[TestAssembly.Nested+Validator]
    E18 --> E18T25[TestAssembly.Request]
    E18 --> E18T26[TestAssembly.RequestHandler]
    E18 --> E18T27[TestAssembly.Response]
    E18 --> E18T28[TestAssembly.Service]
    E18 --> E18T29[TestAssembly.ServiceB]
    E18 --> E18T30[Program]
    F19[Input0.cs:169] --> E19{Reflection}
    E19 --> E19T0[Specular.Abstractions.IReflectionAssemblySelector]
    E19 --> E19T1[Specular.Abstractions.IReflectionTypeSelector]
    E19 --> E19T2[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E19 --> E19T3[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E19 --> E19T4[Specular.Abstractions.IServiceLifetimeSelector]
    E19 --> E19T5[Specular.Abstractions.IServiceTypeSelector]
    E19 --> E19T6[Specular.Abstractions.ITypeFilter]
    E19 --> E19T7[Specular.Abstractions.TypeInfoFilter]
    E19 --> E19T8[Specular.Abstractions.TypeKindFilter]
    E19 --> E19T9[Specular.ScanReportAssembly]
    E19 --> E19T10[Specular.ScanReportType]
    E19 --> E19T11[Specular.ScannerExpression]
    E19 --> E19T12[Specular.ScannerExpressionKind]
    E19 --> E19T13[Specular.SpecularProviderServiceCollectionExtensions]
    E19 --> E19T14[Specular.SpecularScanReport]
    E19 --> E19T15[Specular.SpecularSupport]
    E19 --> E19T16[TestAssembly.GenericService]
    E19 --> E19T17[TestAssembly.GenericServiceB]
    E19 --> E19T18[TestAssembly.IOther]
    E19 --> E19T19[TestAssembly.IService]
    E19 --> E19T20[TestAssembly.IServiceB]
    E19 --> E19T21[TestAssembly.IValidator]
    E19 --> E19T22[TestAssembly.Nested]
    E19 --> E19T23[TestAssembly.Nested+GenericServiceA]
    E19 --> E19T24[TestAssembly.Nested+MyRecord]
    E19 --> E19T25[TestAssembly.Nested+ServiceA]
    E19 --> E19T26[TestAssembly.Nested+Validator]
    E19 --> E19T27[TestAssembly.Request]
    E19 --> E19T28[TestAssembly.RequestHandler]
    E19 --> E19T29[TestAssembly.Response]
    E19 --> E19T30[TestAssembly.Service]
    E19 --> E19T31[TestAssembly.ServiceB]
    E19 --> E19T32[Program]
    F20[Input0.cs:180] --> E20{Reflection}
    E20 --> E20T0[Specular.SpecularSupport]
    F21[Input0.cs:190] --> E21{Reflection}
    E21 --> E21T0[Specular.SpecularSupport]
    F22[Input0.cs:200] --> E22{Reflection}
    E22 --> E22T0[Specular.Abstractions.IReflectionAssemblySelector]
    E22 --> E22T1[Specular.Abstractions.IReflectionTypeSelector]
    E22 --> E22T2[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E22 --> E22T3[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E22 --> E22T4[Specular.Abstractions.IServiceLifetimeSelector]
    E22 --> E22T5[Specular.Abstractions.IServiceTypeSelector]
    E22 --> E22T6[Specular.Abstractions.ITypeFilter]
    E22 --> E22T7[Specular.Abstractions.TypeInfoFilter]
    E22 --> E22T8[Specular.Abstractions.TypeKindFilter]
    E22 --> E22T9[Specular.ScanReportAssembly]
    E22 --> E22T10[Specular.ScanReportType]
    E22 --> E22T11[Specular.ScannerExpression]
    E22 --> E22T12[Specular.ScannerExpressionKind]
    E22 --> E22T13[Specular.SpecularProviderServiceCollectionExtensions]
    E22 --> E22T14[Specular.SpecularScanReport]
    E22 --> E22T15[TestAssembly.GenericService]
    E22 --> E22T16[TestAssembly.GenericServiceB]
    E22 --> E22T17[TestAssembly.IGenericService`1]
    E22 --> E22T18[TestAssembly.IOther]
    E22 --> E22T19[TestAssembly.IRequestHandler`2]
    E22 --> E22T20[TestAssembly.IRequest`1]
    E22 --> E22T21[TestAssembly.IService]
    E22 --> E22T22[TestAssembly.IServiceB]
    E22 --> E22T23[TestAssembly.IValidator]
    E22 --> E22T24[TestAssembly.IValidator`1]
    E22 --> E22T25[TestAssembly.Nested]
    E22 --> E22T26[TestAssembly.Nested+GenericServiceA]
    E22 --> E22T27[TestAssembly.Nested+MyRecord]
    E22 --> E22T28[TestAssembly.Nested+ServiceA]
    E22 --> E22T29[TestAssembly.Nested+Validator]
    E22 --> E22T30[TestAssembly.Request]
    E22 --> E22T31[TestAssembly.RequestHandler]
    E22 --> E22T32[TestAssembly.Response]
    E22 --> E22T33[TestAssembly.Service]
    E22 --> E22T34[TestAssembly.ServiceB]
    E22 --> E22T35[Program]
    F23[Input0.cs:211] --> E23{Reflection}
    E23 --> E23T0[Specular.Abstractions.IReflectionAssemblySelector]
    E23 --> E23T1[Specular.Abstractions.IReflectionTypeSelector]
    E23 --> E23T2[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E23 --> E23T3[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E23 --> E23T4[Specular.Abstractions.IServiceLifetimeSelector]
    E23 --> E23T5[Specular.Abstractions.IServiceTypeSelector]
    E23 --> E23T6[Specular.Abstractions.ITypeFilter]
    E23 --> E23T7[Specular.Abstractions.TypeInfoFilter]
    E23 --> E23T8[Specular.Abstractions.TypeKindFilter]
    E23 --> E23T9[Specular.ScanReportAssembly]
    E23 --> E23T10[Specular.ScanReportType]
    E23 --> E23T11[Specular.ScannerExpression]
    E23 --> E23T12[Specular.ScannerExpressionKind]
    E23 --> E23T13[Specular.SpecularProviderServiceCollectionExtensions]
    E23 --> E23T14[Specular.SpecularScanReport]
    E23 --> E23T15[TestAssembly.GenericService]
    E23 --> E23T16[TestAssembly.GenericServiceB]
    E23 --> E23T17[TestAssembly.IGenericService`1]
    E23 --> E23T18[TestAssembly.IOther]
    E23 --> E23T19[TestAssembly.IRequestHandler`2]
    E23 --> E23T20[TestAssembly.IRequest`1]
    E23 --> E23T21[TestAssembly.IService]
    E23 --> E23T22[TestAssembly.IServiceB]
    E23 --> E23T23[TestAssembly.IValidator]
    E23 --> E23T24[TestAssembly.IValidator`1]
    E23 --> E23T25[TestAssembly.Nested]
    E23 --> E23T26[TestAssembly.Nested+GenericServiceA]
    E23 --> E23T27[TestAssembly.Nested+MyRecord]
    E23 --> E23T28[TestAssembly.Nested+ServiceA]
    E23 --> E23T29[TestAssembly.Nested+Validator]
    E23 --> E23T30[TestAssembly.Request]
    E23 --> E23T31[TestAssembly.RequestHandler]
    E23 --> E23T32[TestAssembly.Response]
    E23 --> E23T33[TestAssembly.Service]
    E23 --> E23T34[TestAssembly.ServiceB]
    E23 --> E23T35[Program]
    F24[Input0.cs:252] --> E24{Reflection}
    E24 --> E24T0[Specular.Abstractions.ExcludeFromSpecularAttribute]
    E24 --> E24T1[Specular.Abstractions.IReflectionAssemblySelector]
    E24 --> E24T2[Specular.Abstractions.IReflectionTypeSelector]
    E24 --> E24T3[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E24 --> E24T4[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E24 --> E24T5[Specular.Abstractions.IServiceLifetimeSelector]
    E24 --> E24T6[Specular.Abstractions.IServiceTypeSelector]
    E24 --> E24T7[Specular.Abstractions.ITypeFilter]
    E24 --> E24T8[Specular.Abstractions.SpecularHashAttribute]
    E24 --> E24T9[Specular.Abstractions.TypeInfoFilter]
    E24 --> E24T10[Specular.Abstractions.TypeKindFilter]
    E24 --> E24T11[Specular.RegistrationLifetimeAttribute]
    E24 --> E24T12[Specular.ServiceRegistrationAttribute]
    E24 --> E24T13[Specular.ServiceRegistrationAttribute`1]
    E24 --> E24T14[Specular.ServiceRegistrationAttribute`2]
    E24 --> E24T15[Specular.ServiceRegistrationAttribute`3]
    E24 --> E24T16[Specular.ServiceRegistrationAttribute`4]
    E24 --> E24T17[Specular.ServiceRegistrationAttribute`5]
    E24 --> E24T18[Specular.ServiceRegistrationAttribute`6]
    E24 --> E24T19[Specular.ServiceRegistrationAttribute`7]
    E24 --> E24T20[Specular.ServiceRegistrationAttribute`8]
    E24 --> E24T21[Specular.SpecularProviderServiceCollectionExtensions]
    E24 --> E24T22[Specular.SpecularSupport]
    E24 --> E24T23[TestAssembly.GenericServiceB]
    E24 --> E24T24[TestAssembly.IGenericService`1]
    E24 --> E24T25[TestAssembly.IOther]
    E24 --> E24T26[TestAssembly.IRequestHandler`2]
    E24 --> E24T27[TestAssembly.IRequest`1]
    E24 --> E24T28[TestAssembly.IService]
    E24 --> E24T29[TestAssembly.IServiceB]
    E24 --> E24T30[TestAssembly.IValidator]
    E24 --> E24T31[TestAssembly.IValidator`1]
    E24 --> E24T32[TestAssembly.Nested]
    E24 --> E24T33[TestAssembly.Nested+GenericServiceA]
    E24 --> E24T34[TestAssembly.Nested+ServiceA]
    E24 --> E24T35[TestAssembly.Service]
    F25[Input0.cs:262] --> E25{ServiceDescriptor}
    E25 --> E25T0[TestAssembly.Service]
    F26[Input0.cs:268] --> E26{ServiceDescriptor}
    E26 --> E26T0[TestAssembly.Nested+ServiceA]
    E26 --> E26T1[TestAssembly.Service]
    E26 --> E26T2[TestAssembly.ServiceB]
    F27[Input0.cs:274] --> E27{ServiceDescriptor}
    E27 --> E27T0[TestAssembly.Nested+ServiceA]
    E27 --> E27T1[TestAssembly.Service]
    E27 --> E27T2[TestAssembly.ServiceB]
    F28[Input0.cs:279] --> E28{ServiceDescriptor}
    E28 --> E28T0[TestAssembly.Nested+ServiceA]
    E28 --> E28T1[TestAssembly.Service]
    E28 --> E28T2[TestAssembly.ServiceB]
    F29[Input0.cs:285] --> E29{ServiceDescriptor}
    E29 --> E29T0[TestAssembly.Nested+ServiceA]
    E29 --> E29T1[TestAssembly.Service]
    E29 --> E29T2[TestAssembly.ServiceB]
    F30[Input0.cs:291] --> E30{ServiceDescriptor}
    E30 --> E30T0[TestAssembly.GenericService]
    E30 --> E30T1[TestAssembly.GenericServiceB]
    E30 --> E30T2[TestAssembly.Nested+GenericServiceA]
    F31[Input0.cs:296] --> E31{ServiceDescriptor}
    E31 --> E31T0[TestAssembly.GenericService]
    E31 --> E31T1[TestAssembly.GenericServiceB]
    E31 --> E31T2[TestAssembly.Nested+GenericServiceA]
    F32[Input0.cs:302] --> E32{ServiceDescriptor}
    E32 --> E32T0[TestAssembly.RequestHandler]
    F33[Input0.cs:307] --> E33{ServiceDescriptor}
    E33 --> E33T0[TestAssembly.Service]
    F34[Input0.cs:313] --> E34{ServiceDescriptor}
    E34 --> E34T0[TestAssembly.Nested+ServiceA]
    E34 --> E34T1[TestAssembly.Service]
    E34 --> E34T2[TestAssembly.ServiceB]
    F35[Input0.cs:319] --> E35{ServiceDescriptor}
    E35 --> E35T0[TestAssembly.Nested+ServiceA]
    E35 --> E35T1[TestAssembly.Service]
    E35 --> E35T2[TestAssembly.ServiceB]
    F36[Input0.cs:325] --> E36{ServiceDescriptor}
    E36 --> E36T0[TestAssembly.GenericService]
    E36 --> E36T1[TestAssembly.GenericServiceB]
    E36 --> E36T2[TestAssembly.Nested+GenericServiceA]
    F37[Input0.cs:331] --> E37{ServiceDescriptor}
    E37 --> E37T0[TestAssembly.Nested+Validator]
    F38[Input0.cs:336] --> E38{ServiceDescriptor}
    E38 --> E38T0[TestAssembly.Nested+ServiceA]
    E38 --> E38T1[TestAssembly.Service]
    E38 --> E38T2[TestAssembly.ServiceB]
    F39[Input0.cs:341] --> E39{ServiceDescriptor}
    E39 --> E39T0[TestAssembly.GenericService]
    E39 --> E39T1[TestAssembly.GenericServiceB]
    E39 --> E39T2[TestAssembly.Nested+GenericServiceA]
    F40[Input0.cs:347] --> E40{ServiceDescriptor}
    E40 --> E40T0[TestAssembly.GenericService]
    E40 --> E40T1[TestAssembly.GenericServiceB]
    E40 --> E40T2[TestAssembly.Nested+GenericServiceA]
    F41[Input0.cs:366] --> E41{ServiceDescriptor}
    E41 --> E41T0[TestAssembly.GenericService]
    E41 --> E41T1[TestAssembly.GenericServiceB]
    E41 --> E41T2[TestAssembly.Nested+GenericServiceA]
    E41 --> E41T3[TestAssembly.Nested+MyRecord]
    E41 --> E41T4[TestAssembly.Nested+ServiceA]
    E41 --> E41T5[TestAssembly.Nested+Validator]
    E41 --> E41T6[TestAssembly.Request]
    E41 --> E41T7[TestAssembly.RequestHandler]
    E41 --> E41T8[TestAssembly.Response]
    E41 --> E41T9[TestAssembly.Service]
    E41 --> E41T10[TestAssembly.ServiceB]
";
}
#nullable restore
