//HintName: Specular.Analyzers/Specular.Analyzers.SpecularProviderGenerator/SpecularScanReport.g.cs
#nullable enable
using System;
using System.Collections.Generic;
using System.Reflection;

namespace Specular;
[System.Runtime.CompilerServices.CompilerGenerated, Microsoft.CodeAnalysis.EmbeddedAttribute]
internal enum ScannerExpressionKind
{
    Assembly,
    Reflection,
    ServiceDescriptor
}

[System.Runtime.CompilerServices.CompilerGenerated, Microsoft.CodeAnalysis.EmbeddedAttribute, System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed record ScanReportType(string AssemblyName, string TypeName, Type? Type);
[System.Runtime.CompilerServices.CompilerGenerated, Microsoft.CodeAnalysis.EmbeddedAttribute, System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed record ScanReportAssembly(string AssemblyName, Assembly? Assembly);
[System.Runtime.CompilerServices.CompilerGenerated, Microsoft.CodeAnalysis.EmbeddedAttribute, System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed record ScannerExpression(ScannerExpressionKind Kind, string FilePath, int LineNumber, string SelectorText, IReadOnlyList<ScanReportAssembly> DiscoveredAssemblies, IReadOnlyList<ScanReportType> DiscoveredTypes);
[System.Runtime.CompilerServices.CompilerGenerated, Microsoft.CodeAnalysis.EmbeddedAttribute, System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal static class SpecularScanReport
{
    public static IReadOnlyList<ScannerExpression> Entries { get; } = new ScannerExpression[]
    {
        new(ScannerExpressionKind.Assembly, "Input0.cs", 16, "z => z.FromAssemblies()", new ScanReportAssembly[] { new("OtherProject", null), new("Specular", typeof(global::Specular.ISpecularProvider).Assembly), new("System.ComponentModel", typeof(global::System.IServiceProvider).Assembly), new("TestAssembly", typeof(global::TestAssembly.IService).Assembly), new("TestProject", null) }, new ScanReportType[] { }),
        new(ScannerExpressionKind.Assembly, "Input0.cs", 17, "z => z.FromAssemblies().NotFromAssemblyOf<ServiceRegistrationAttribute>()", new ScanReportAssembly[] { new("OtherProject", null), new("Specular", typeof(global::Specular.ISpecularProvider).Assembly), new("System.ComponentModel", typeof(global::System.IServiceProvider).Assembly), new("TestAssembly", typeof(global::TestAssembly.IService).Assembly), new("TestProject", null) }, new ScanReportType[] { }),
        new(ScannerExpressionKind.Assembly, "Input0.cs", 18, "z => z.FromAssemblies().NotFromAssemblyOf<IService>()", new ScanReportAssembly[] { new("OtherProject", null), new("Specular", typeof(global::Specular.ISpecularProvider).Assembly), new("System.ComponentModel", typeof(global::System.IServiceProvider).Assembly), new("TestAssembly", typeof(global::TestAssembly.IService).Assembly), new("TestProject", null) }, new ScanReportType[] { }),
        new(ScannerExpressionKind.Assembly, "Input0.cs", 19, "z => z.EntryAssembly()", new ScanReportAssembly[] { new("OtherProject", null) }, new ScanReportType[] { }),
        new(ScannerExpressionKind.Assembly, "Input0.cs", 20, "z => z.DependenciesFromAssemblyOf<ServiceRegistrationAttribute>()", new ScanReportAssembly[] { new("OtherProject", null), new("TestProject", null) }, new ScanReportType[] { }),
        new(ScannerExpressionKind.Assembly, "Input0.cs", 21, "z => z.DependenciesFromAssemblyOf<IService>()", new ScanReportAssembly[] { new("OtherProject", null), new("TestProject", null) }, new ScanReportType[] { }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 22, "z => z\n                .FromAssemblies()\n                .NotFromAssemblyOf<ServiceRegistrationAttribute>()\n                .GetTypes(\n                     x => x\n                         .NotAssignableTo<ISpecularProvider>()\n                         .NotKindOf(TypeKindFilter.Delegate, TypeKindFilter.Class)\n                         .NotInNamespaces(\"JetBrains.Annotations\", \"Polyfills\", \"System\")\n                         .NotStartsWith(\"Polyfill\")\n                 )", new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", typeof(global::Specular.Abstractions.IReflectionAssemblySelector)), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", typeof(global::Specular.Abstractions.IReflectionTypeSelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", typeof(global::Specular.Abstractions.IServiceDescriptorAssemblySelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", typeof(global::Specular.Abstractions.IServiceDescriptorTypeSelector)), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", typeof(global::Specular.Abstractions.IServiceLifetimeSelector)), new("Specular", "Specular.Abstractions.IServiceTypeSelector", typeof(global::Specular.Abstractions.IServiceTypeSelector)), new("Specular", "Specular.Abstractions.ITypeFilter", typeof(global::Specular.Abstractions.ITypeFilter)), new("Specular", "Specular.Abstractions.TypeInfoFilter", typeof(global::Specular.Abstractions.TypeInfoFilter)), new("Specular", "Specular.Abstractions.TypeKindFilter", typeof(global::Specular.Abstractions.TypeKindFilter)), new("TestAssembly", "TestAssembly.IGenericService`1", typeof(global::TestAssembly.IGenericService<>)), new("TestAssembly", "TestAssembly.IOther", typeof(global::TestAssembly.IOther)), new("TestAssembly", "TestAssembly.IRequestHandler`2", typeof(global::TestAssembly.IRequestHandler<, >)), new("TestAssembly", "TestAssembly.IRequest`1", typeof(global::TestAssembly.IRequest<>)), new("TestAssembly", "TestAssembly.IService", typeof(global::TestAssembly.IService)), new("TestAssembly", "TestAssembly.IServiceB", typeof(global::TestAssembly.IServiceB)), new("TestAssembly", "TestAssembly.IValidator", typeof(global::TestAssembly.IValidator)), new("TestAssembly", "TestAssembly.IValidator`1", typeof(global::TestAssembly.IValidator<>)) }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 32, "z => z\n                .FromAssemblies()\n                .NotFromAssemblyOf<ServiceRegistrationAttribute>()\n                .GetTypes(\n                     x => x\n                         .NotAssignableTo<ISpecularProvider>()\n                         .NotKindOf(TypeKindFilter.Delegate, TypeKindFilter.Class, TypeKindFilter.Enum)\n                         .NotInNamespaces(\"JetBrains.Annotations\", \"Polyfills\", \"System\")\n                         .NotStartsWith(\"Polyfill\")\n                 )", new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", typeof(global::Specular.Abstractions.IReflectionAssemblySelector)), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", typeof(global::Specular.Abstractions.IReflectionTypeSelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", typeof(global::Specular.Abstractions.IServiceDescriptorAssemblySelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", typeof(global::Specular.Abstractions.IServiceDescriptorTypeSelector)), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", typeof(global::Specular.Abstractions.IServiceLifetimeSelector)), new("Specular", "Specular.Abstractions.IServiceTypeSelector", typeof(global::Specular.Abstractions.IServiceTypeSelector)), new("Specular", "Specular.Abstractions.ITypeFilter", typeof(global::Specular.Abstractions.ITypeFilter)), new("TestAssembly", "TestAssembly.IGenericService`1", typeof(global::TestAssembly.IGenericService<>)), new("TestAssembly", "TestAssembly.IOther", typeof(global::TestAssembly.IOther)), new("TestAssembly", "TestAssembly.IRequestHandler`2", typeof(global::TestAssembly.IRequestHandler<, >)), new("TestAssembly", "TestAssembly.IRequest`1", typeof(global::TestAssembly.IRequest<>)), new("TestAssembly", "TestAssembly.IService", typeof(global::TestAssembly.IService)), new("TestAssembly", "TestAssembly.IServiceB", typeof(global::TestAssembly.IServiceB)), new("TestAssembly", "TestAssembly.IValidator", typeof(global::TestAssembly.IValidator)), new("TestAssembly", "TestAssembly.IValidator`1", typeof(global::TestAssembly.IValidator<>)) }),
        new(ScannerExpressionKind.Reflection, "{scrubbed}"),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 52, "z => z\n                .FromAssemblies()\n                .NotFromAssemblyOf<ServiceRegistrationAttribute>()\n                .GetTypes(\n                     x => x\n                         .NotAssignableTo<ISpecularProvider>()\n                         .InfoOf(TypeInfoFilter.Abstract)\n                         .NotInNamespaces(\"JetBrains.Annotations\", \"Polyfills\", \"System\")\n                         .NotStartsWith(\"Polyfill\")\n                 )", new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", typeof(global::Specular.Abstractions.IReflectionAssemblySelector)), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", typeof(global::Specular.Abstractions.IReflectionTypeSelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", typeof(global::Specular.Abstractions.IServiceDescriptorAssemblySelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", typeof(global::Specular.Abstractions.IServiceDescriptorTypeSelector)), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", typeof(global::Specular.Abstractions.IServiceLifetimeSelector)), new("Specular", "Specular.Abstractions.IServiceTypeSelector", typeof(global::Specular.Abstractions.IServiceTypeSelector)), new("Specular", "Specular.Abstractions.ITypeFilter", typeof(global::Specular.Abstractions.ITypeFilter)), new("TestAssembly", "TestAssembly.IGenericService`1", typeof(global::TestAssembly.IGenericService<>)), new("TestAssembly", "TestAssembly.IOther", typeof(global::TestAssembly.IOther)), new("TestAssembly", "TestAssembly.IRequestHandler`2", typeof(global::TestAssembly.IRequestHandler<, >)), new("TestAssembly", "TestAssembly.IRequest`1", typeof(global::TestAssembly.IRequest<>)), new("TestAssembly", "TestAssembly.IService", typeof(global::TestAssembly.IService)), new("TestAssembly", "TestAssembly.IServiceB", typeof(global::TestAssembly.IServiceB)), new("TestAssembly", "TestAssembly.IValidator", typeof(global::TestAssembly.IValidator)), new("TestAssembly", "TestAssembly.IValidator`1", typeof(global::TestAssembly.IValidator<>)) }),
        new(ScannerExpressionKind.Reflection, "{scrubbed}"),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 72, "z => z\n                .FromAssemblies()\n                .NotFromAssemblyOf<ServiceRegistrationAttribute>()\n                .GetTypes(\n                     x => x\n                         .NotAssignableTo<ISpecularProvider>()\n                         .InfoOf(TypeInfoFilter.ValueType)\n                         .NotInNamespaces(\"JetBrains.Annotations\", \"Polyfills\", \"System\")\n                         .NotStartsWith(\"Polyfill\")\n                 )", new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.Abstractions.TypeInfoFilter", typeof(global::Specular.Abstractions.TypeInfoFilter)), new("Specular", "Specular.Abstractions.TypeKindFilter", typeof(global::Specular.Abstractions.TypeKindFilter)) }),
        new(ScannerExpressionKind.Reflection, "{scrubbed}"),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 92, "z => z\n                .FromAssemblies()\n                .NotFromAssemblyOf<ServiceRegistrationAttribute>()\n                .GetTypes(\n                     x => x\n                         .NotAssignableTo<ISpecularProvider>()\n                         .InfoOf(TypeInfoFilter.Static)\n                         .NotInNamespaces(\"JetBrains.Annotations\", \"Polyfills\", \"System\")\n                         .NotStartsWith(\"Polyfill\")\n                 )", new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "MyAssembly", null), new("Specular", "MyAssembly+Info", null), new("Specular", "MyAssembly+Metadata", null), new("Specular", "MyAssembly+Project", null), new("Specular", "Specular.SpecularProviderServiceCollectionExtensions", typeof(global::Specular.SpecularProviderServiceCollectionExtensions)), new("Specular", "Specular.SpecularSupport", typeof(global::Specular.SpecularSupport)), new("TestAssembly", "MyAssembly", null), new("TestAssembly", "MyAssembly+Info", null), new("TestAssembly", "MyAssembly+Metadata", null), new("TestAssembly", "MyAssembly+Project", null), new("TestAssembly", "TestAssembly.Nested", typeof(global::TestAssembly.Nested)) }),
        new(ScannerExpressionKind.Reflection, "{scrubbed}"),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 112, "z => z\n                .FromAssemblies()\n                .NotFromAssemblyOf<ServiceRegistrationAttribute>()\n                .GetTypes(\n                     x => x\n                         .NotAssignableTo<ISpecularProvider>()\n                         .InfoOf(TypeInfoFilter.GenericType)\n                         .NotInNamespaces(\"JetBrains.Annotations\", \"Polyfills\", \"System\")\n                         .NotStartsWith(\"Polyfill\")\n                 )", new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.ServiceRegistrationAttribute`1", typeof(global::Specular.ServiceRegistrationAttribute<>)), new("Specular", "Specular.ServiceRegistrationAttribute`2", typeof(global::Specular.ServiceRegistrationAttribute<, >)), new("Specular", "Specular.ServiceRegistrationAttribute`3", typeof(global::Specular.ServiceRegistrationAttribute<,, >)), new("Specular", "Specular.ServiceRegistrationAttribute`4", typeof(global::Specular.ServiceRegistrationAttribute<,,, >)), new("Specular", "Specular.ServiceRegistrationAttribute`5", typeof(global::Specular.ServiceRegistrationAttribute<,,,, >)), new("Specular", "Specular.ServiceRegistrationAttribute`6", typeof(global::Specular.ServiceRegistrationAttribute<,,,,, >)), new("Specular", "Specular.ServiceRegistrationAttribute`7", typeof(global::Specular.ServiceRegistrationAttribute<,,,,,, >)), new("Specular", "Specular.ServiceRegistrationAttribute`8", typeof(global::Specular.ServiceRegistrationAttribute<,,,,,,, >)), new("TestAssembly", "TestAssembly.IGenericService`1", typeof(global::TestAssembly.IGenericService<>)), new("TestAssembly", "TestAssembly.IRequestHandler`2", typeof(global::TestAssembly.IRequestHandler<, >)), new("TestAssembly", "TestAssembly.IRequest`1", typeof(global::TestAssembly.IRequest<>)), new("TestAssembly", "TestAssembly.IValidator`1", typeof(global::TestAssembly.IValidator<>)) }),
        new(ScannerExpressionKind.Reflection, "{scrubbed}"),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 132, "z => z\n                .FromAssemblies()\n                .NotFromAssemblyOf<ServiceRegistrationAttribute>()\n                .GetTypes(\n                     x => x\n                         .NotAssignableTo<ISpecularProvider>()\n                         .NotInfoOf(TypeInfoFilter.Visible)\n                         .NotAssignableTo<Attribute>()\n                         .NotInNamespaces(\"JetBrains.Annotations\", \"Polyfills\", \"System\")\n                         .NotStartsWith(\"Polyfill\")\n                 )", new ScanReportAssembly[] { }, new ScanReportType[] { new("OtherProject", "Program", null), new("Specular", "MyAssembly", null), new("Specular", "MyAssembly+Info", null), new("Specular", "MyAssembly+Metadata", null), new("Specular", "MyAssembly+Project", null), new("TestAssembly", "MyAssembly", null), new("TestAssembly", "MyAssembly+Info", null), new("TestAssembly", "MyAssembly+Metadata", null), new("TestAssembly", "MyAssembly+Project", null), new("TestAssembly", "TestAssembly.GenericService", null), new("TestAssembly", "TestAssembly.Nested+MyRecord", null), new("TestAssembly", "TestAssembly.Nested+Validator", null), new("TestAssembly", "TestAssembly.Request", null), new("TestAssembly", "TestAssembly.RequestHandler", null), new("TestAssembly", "TestAssembly.Response", null), new("TestAssembly", "TestAssembly.ServiceB", null) }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 147, "z => z\n                .FromAssemblies()\n                .NotFromAssemblyOf<ServiceRegistrationAttribute>()\n                .GetTypes(\n                     x => x\n                         .NotAssignableTo<ISpecularProvider>()\n                         .NotInfoOf(TypeInfoFilter.ValueType)\n                         .NotAssignableTo<Attribute>()\n                         .NotInNamespaces(\"JetBrains.Annotations\", \"Polyfills\", \"System\")\n                         .NotStartsWith(\"Polyfill\")\n                 )", new ScanReportAssembly[] { }, new ScanReportType[] { new("OtherProject", "Program", null), new("Specular", "MyAssembly", null), new("Specular", "MyAssembly+Info", null), new("Specular", "MyAssembly+Metadata", null), new("Specular", "MyAssembly+Project", null), new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", typeof(global::Specular.Abstractions.IReflectionAssemblySelector)), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", typeof(global::Specular.Abstractions.IReflectionTypeSelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", typeof(global::Specular.Abstractions.IServiceDescriptorAssemblySelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", typeof(global::Specular.Abstractions.IServiceDescriptorTypeSelector)), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", typeof(global::Specular.Abstractions.IServiceLifetimeSelector)), new("Specular", "Specular.Abstractions.IServiceTypeSelector", typeof(global::Specular.Abstractions.IServiceTypeSelector)), new("Specular", "Specular.Abstractions.ITypeFilter", typeof(global::Specular.Abstractions.ITypeFilter)), new("Specular", "Specular.SpecularProviderServiceCollectionExtensions", typeof(global::Specular.SpecularProviderServiceCollectionExtensions)), new("Specular", "Specular.SpecularSupport", typeof(global::Specular.SpecularSupport)), new("TestAssembly", "MyAssembly", null), new("TestAssembly", "MyAssembly+Info", null), new("TestAssembly", "MyAssembly+Metadata", null), new("TestAssembly", "MyAssembly+Project", null), new("TestAssembly", "TestAssembly.GenericService", null), new("TestAssembly", "TestAssembly.GenericServiceB", typeof(global::TestAssembly.GenericServiceB)), new("TestAssembly", "TestAssembly.IGenericService`1", typeof(global::TestAssembly.IGenericService<>)), new("TestAssembly", "TestAssembly.IOther", typeof(global::TestAssembly.IOther)), new("TestAssembly", "TestAssembly.IRequestHandler`2", typeof(global::TestAssembly.IRequestHandler<, >)), new("TestAssembly", "TestAssembly.IRequest`1", typeof(global::TestAssembly.IRequest<>)), new("TestAssembly", "TestAssembly.IService", typeof(global::TestAssembly.IService)), new("TestAssembly", "TestAssembly.IServiceB", typeof(global::TestAssembly.IServiceB)), new("TestAssembly", "TestAssembly.IValidator", typeof(global::TestAssembly.IValidator)), new("TestAssembly", "TestAssembly.IValidator`1", typeof(global::TestAssembly.IValidator<>)), new("TestAssembly", "TestAssembly.Nested", typeof(global::TestAssembly.Nested)), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", typeof(global::TestAssembly.Nested.GenericServiceA)), new("TestAssembly", "TestAssembly.Nested+MyRecord", null), new("TestAssembly", "TestAssembly.Nested+ServiceA", typeof(global::TestAssembly.Nested.ServiceA)), new("TestAssembly", "TestAssembly.Nested+Validator", null), new("TestAssembly", "TestAssembly.Request", null), new("TestAssembly", "TestAssembly.RequestHandler", null), new("TestAssembly", "TestAssembly.Response", null), new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)), new("TestAssembly", "TestAssembly.ServiceB", null) }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 158, "z => z\n                .FromAssemblies()\n                .NotFromAssemblyOf<ServiceRegistrationAttribute>()\n                .GetTypes(\n                     x => x\n                         .NotAssignableTo<ISpecularProvider>()\n                         .NotInfoOf(TypeInfoFilter.Sealed)\n                         .NotAssignableTo<Attribute>()\n                         .NotInNamespaces(\"JetBrains.Annotations\", \"Polyfills\", \"System\")\n                         .NotStartsWith(\"Polyfill\")\n                 )", new ScanReportAssembly[] { }, new ScanReportType[] { new("OtherProject", "Program", null), new("Specular", "MyAssembly", null), new("Specular", "MyAssembly+Info", null), new("Specular", "MyAssembly+Metadata", null), new("Specular", "MyAssembly+Project", null), new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", typeof(global::Specular.Abstractions.IReflectionAssemblySelector)), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", typeof(global::Specular.Abstractions.IReflectionTypeSelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", typeof(global::Specular.Abstractions.IServiceDescriptorAssemblySelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", typeof(global::Specular.Abstractions.IServiceDescriptorTypeSelector)), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", typeof(global::Specular.Abstractions.IServiceLifetimeSelector)), new("Specular", "Specular.Abstractions.IServiceTypeSelector", typeof(global::Specular.Abstractions.IServiceTypeSelector)), new("Specular", "Specular.Abstractions.ITypeFilter", typeof(global::Specular.Abstractions.ITypeFilter)), new("Specular", "Specular.SpecularProviderServiceCollectionExtensions", typeof(global::Specular.SpecularProviderServiceCollectionExtensions)), new("Specular", "Specular.SpecularSupport", typeof(global::Specular.SpecularSupport)), new("TestAssembly", "MyAssembly", null), new("TestAssembly", "MyAssembly+Info", null), new("TestAssembly", "MyAssembly+Metadata", null), new("TestAssembly", "MyAssembly+Project", null), new("TestAssembly", "TestAssembly.GenericService", null), new("TestAssembly", "TestAssembly.GenericServiceB", typeof(global::TestAssembly.GenericServiceB)), new("TestAssembly", "TestAssembly.IGenericService`1", typeof(global::TestAssembly.IGenericService<>)), new("TestAssembly", "TestAssembly.IOther", typeof(global::TestAssembly.IOther)), new("TestAssembly", "TestAssembly.IRequestHandler`2", typeof(global::TestAssembly.IRequestHandler<, >)), new("TestAssembly", "TestAssembly.IRequest`1", typeof(global::TestAssembly.IRequest<>)), new("TestAssembly", "TestAssembly.IService", typeof(global::TestAssembly.IService)), new("TestAssembly", "TestAssembly.IServiceB", typeof(global::TestAssembly.IServiceB)), new("TestAssembly", "TestAssembly.IValidator", typeof(global::TestAssembly.IValidator)), new("TestAssembly", "TestAssembly.IValidator`1", typeof(global::TestAssembly.IValidator<>)), new("TestAssembly", "TestAssembly.Nested", typeof(global::TestAssembly.Nested)), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", typeof(global::TestAssembly.Nested.GenericServiceA)), new("TestAssembly", "TestAssembly.Nested+MyRecord", null), new("TestAssembly", "TestAssembly.Nested+ServiceA", typeof(global::TestAssembly.Nested.ServiceA)), new("TestAssembly", "TestAssembly.Nested+Validator", null), new("TestAssembly", "TestAssembly.Request", null), new("TestAssembly", "TestAssembly.RequestHandler", null), new("TestAssembly", "TestAssembly.Response", null), new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)), new("TestAssembly", "TestAssembly.ServiceB", null) }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 169, "z => z\n                .FromAssemblies()\n                .NotFromAssemblyOf<ServiceRegistrationAttribute>()\n                .GetTypes(\n                     x => x\n                         .NotAssignableTo<ISpecularProvider>()\n                         .NotInfoOf(TypeInfoFilter.GenericType)\n                         .NotAssignableTo<Attribute>()\n                         .NotInNamespaces(\"JetBrains.Annotations\", \"Polyfills\", \"System\")\n                         .NotStartsWith(\"Polyfill\")\n                 )", new ScanReportAssembly[] { }, new ScanReportType[] { new("OtherProject", "Program", null), new("Specular", "MyAssembly", null), new("Specular", "MyAssembly+Info", null), new("Specular", "MyAssembly+Metadata", null), new("Specular", "MyAssembly+Project", null), new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", typeof(global::Specular.Abstractions.IReflectionAssemblySelector)), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", typeof(global::Specular.Abstractions.IReflectionTypeSelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", typeof(global::Specular.Abstractions.IServiceDescriptorAssemblySelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", typeof(global::Specular.Abstractions.IServiceDescriptorTypeSelector)), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", typeof(global::Specular.Abstractions.IServiceLifetimeSelector)), new("Specular", "Specular.Abstractions.IServiceTypeSelector", typeof(global::Specular.Abstractions.IServiceTypeSelector)), new("Specular", "Specular.Abstractions.ITypeFilter", typeof(global::Specular.Abstractions.ITypeFilter)), new("Specular", "Specular.Abstractions.TypeInfoFilter", typeof(global::Specular.Abstractions.TypeInfoFilter)), new("Specular", "Specular.Abstractions.TypeKindFilter", typeof(global::Specular.Abstractions.TypeKindFilter)), new("Specular", "Specular.SpecularProviderServiceCollectionExtensions", typeof(global::Specular.SpecularProviderServiceCollectionExtensions)), new("Specular", "Specular.SpecularSupport", typeof(global::Specular.SpecularSupport)), new("TestAssembly", "MyAssembly", null), new("TestAssembly", "MyAssembly+Info", null), new("TestAssembly", "MyAssembly+Metadata", null), new("TestAssembly", "MyAssembly+Project", null), new("TestAssembly", "TestAssembly.GenericService", null), new("TestAssembly", "TestAssembly.GenericServiceB", typeof(global::TestAssembly.GenericServiceB)), new("TestAssembly", "TestAssembly.IOther", typeof(global::TestAssembly.IOther)), new("TestAssembly", "TestAssembly.IService", typeof(global::TestAssembly.IService)), new("TestAssembly", "TestAssembly.IServiceB", typeof(global::TestAssembly.IServiceB)), new("TestAssembly", "TestAssembly.IValidator", typeof(global::TestAssembly.IValidator)), new("TestAssembly", "TestAssembly.Nested", typeof(global::TestAssembly.Nested)), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", typeof(global::TestAssembly.Nested.GenericServiceA)), new("TestAssembly", "TestAssembly.Nested+MyRecord", null), new("TestAssembly", "TestAssembly.Nested+ServiceA", typeof(global::TestAssembly.Nested.ServiceA)), new("TestAssembly", "TestAssembly.Nested+Validator", null), new("TestAssembly", "TestAssembly.Request", null), new("TestAssembly", "TestAssembly.RequestHandler", null), new("TestAssembly", "TestAssembly.Response", null), new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)), new("TestAssembly", "TestAssembly.ServiceB", null) }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 180, "z => z\n                .FromAssemblies()\n                .NotFromAssemblyOf<ServiceRegistrationAttribute>()\n                .GetTypes(\n                     x => x\n                         .NotAssignableTo<ISpecularProvider>()\n                         .WithAttribute(typeof(EditorBrowsableAttribute))\n                         .NotInNamespaces(\"JetBrains.Annotations\", \"Polyfills\", \"System\")\n                         .NotStartsWith(\"Polyfill\")\n                 )", new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.SpecularSupport", typeof(global::Specular.SpecularSupport)) }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 190, "z => z\n                .FromAssemblies()\n                .NotFromAssemblyOf<ServiceRegistrationAttribute>()\n                .GetTypes(\n                     x => x\n                         .NotAssignableTo<ISpecularProvider>()\n                         .WithAttribute<EditorBrowsableAttribute>()\n                         .NotInNamespaces(\"JetBrains.Annotations\", \"Polyfills\", \"System\")\n                         .NotStartsWith(\"Polyfill\")\n                 )", new ScanReportAssembly[] { }, new ScanReportType[] { new("Specular", "Specular.SpecularSupport", typeof(global::Specular.SpecularSupport)) }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 200, "z => z\n                .FromAssemblies()\n                .NotFromAssemblyOf<ServiceRegistrationAttribute>()\n                .GetTypes(\n                     x => x\n                         .NotAssignableTo<ISpecularProvider>()\n                         .WithoutAttribute(typeof(EditorBrowsableAttribute))\n                         .NotAssignableTo(typeof(Attribute))\n                         .NotInNamespaces(\"JetBrains.Annotations\", \"Polyfills\", \"System\")\n                         .NotStartsWith(\"Polyfill\")\n                 )", new ScanReportAssembly[] { }, new ScanReportType[] { new("OtherProject", "Program", null), new("Specular", "MyAssembly", null), new("Specular", "MyAssembly+Info", null), new("Specular", "MyAssembly+Metadata", null), new("Specular", "MyAssembly+Project", null), new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", typeof(global::Specular.Abstractions.IReflectionAssemblySelector)), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", typeof(global::Specular.Abstractions.IReflectionTypeSelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", typeof(global::Specular.Abstractions.IServiceDescriptorAssemblySelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", typeof(global::Specular.Abstractions.IServiceDescriptorTypeSelector)), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", typeof(global::Specular.Abstractions.IServiceLifetimeSelector)), new("Specular", "Specular.Abstractions.IServiceTypeSelector", typeof(global::Specular.Abstractions.IServiceTypeSelector)), new("Specular", "Specular.Abstractions.ITypeFilter", typeof(global::Specular.Abstractions.ITypeFilter)), new("Specular", "Specular.Abstractions.TypeInfoFilter", typeof(global::Specular.Abstractions.TypeInfoFilter)), new("Specular", "Specular.Abstractions.TypeKindFilter", typeof(global::Specular.Abstractions.TypeKindFilter)), new("Specular", "Specular.SpecularProviderServiceCollectionExtensions", typeof(global::Specular.SpecularProviderServiceCollectionExtensions)), new("TestAssembly", "MyAssembly", null), new("TestAssembly", "MyAssembly+Info", null), new("TestAssembly", "MyAssembly+Metadata", null), new("TestAssembly", "MyAssembly+Project", null), new("TestAssembly", "TestAssembly.GenericService", null), new("TestAssembly", "TestAssembly.GenericServiceB", typeof(global::TestAssembly.GenericServiceB)), new("TestAssembly", "TestAssembly.IGenericService`1", typeof(global::TestAssembly.IGenericService<>)), new("TestAssembly", "TestAssembly.IOther", typeof(global::TestAssembly.IOther)), new("TestAssembly", "TestAssembly.IRequestHandler`2", typeof(global::TestAssembly.IRequestHandler<, >)), new("TestAssembly", "TestAssembly.IRequest`1", typeof(global::TestAssembly.IRequest<>)), new("TestAssembly", "TestAssembly.IService", typeof(global::TestAssembly.IService)), new("TestAssembly", "TestAssembly.IServiceB", typeof(global::TestAssembly.IServiceB)), new("TestAssembly", "TestAssembly.IValidator", typeof(global::TestAssembly.IValidator)), new("TestAssembly", "TestAssembly.IValidator`1", typeof(global::TestAssembly.IValidator<>)), new("TestAssembly", "TestAssembly.Nested", typeof(global::TestAssembly.Nested)), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", typeof(global::TestAssembly.Nested.GenericServiceA)), new("TestAssembly", "TestAssembly.Nested+MyRecord", null), new("TestAssembly", "TestAssembly.Nested+ServiceA", typeof(global::TestAssembly.Nested.ServiceA)), new("TestAssembly", "TestAssembly.Nested+Validator", null), new("TestAssembly", "TestAssembly.Request", null), new("TestAssembly", "TestAssembly.RequestHandler", null), new("TestAssembly", "TestAssembly.Response", null), new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)), new("TestAssembly", "TestAssembly.ServiceB", null) }),
        new(ScannerExpressionKind.Reflection, "Input0.cs", 211, "z => z\n                .FromAssemblies()\n                .NotFromAssemblyOf<ServiceRegistrationAttribute>()\n                .GetTypes(\n                     x => x\n                         .NotAssignableTo<ISpecularProvider>()\n                         .WithoutAttribute<EditorBrowsableAttribute>()\n                         .NotAssignableTo<Attribute>()\n                         .NotInNamespaces(\"JetBrains.Annotations\", \"Polyfills\", \"System\")\n                         .NotStartsWith(\"Polyfill\")\n                 )", new ScanReportAssembly[] { }, new ScanReportType[] { new("OtherProject", "Program", null), new("Specular", "MyAssembly", null), new("Specular", "MyAssembly+Info", null), new("Specular", "MyAssembly+Metadata", null), new("Specular", "MyAssembly+Project", null), new("Specular", "Specular.Abstractions.IReflectionAssemblySelector", typeof(global::Specular.Abstractions.IReflectionAssemblySelector)), new("Specular", "Specular.Abstractions.IReflectionTypeSelector", typeof(global::Specular.Abstractions.IReflectionTypeSelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorAssemblySelector", typeof(global::Specular.Abstractions.IServiceDescriptorAssemblySelector)), new("Specular", "Specular.Abstractions.IServiceDescriptorTypeSelector", typeof(global::Specular.Abstractions.IServiceDescriptorTypeSelector)), new("Specular", "Specular.Abstractions.IServiceLifetimeSelector", typeof(global::Specular.Abstractions.IServiceLifetimeSelector)), new("Specular", "Specular.Abstractions.IServiceTypeSelector", typeof(global::Specular.Abstractions.IServiceTypeSelector)), new("Specular", "Specular.Abstractions.ITypeFilter", typeof(global::Specular.Abstractions.ITypeFilter)), new("Specular", "Specular.Abstractions.TypeInfoFilter", typeof(global::Specular.Abstractions.TypeInfoFilter)), new("Specular", "Specular.Abstractions.TypeKindFilter", typeof(global::Specular.Abstractions.TypeKindFilter)), new("Specular", "Specular.SpecularProviderServiceCollectionExtensions", typeof(global::Specular.SpecularProviderServiceCollectionExtensions)), new("TestAssembly", "MyAssembly", null), new("TestAssembly", "MyAssembly+Info", null), new("TestAssembly", "MyAssembly+Metadata", null), new("TestAssembly", "MyAssembly+Project", null), new("TestAssembly", "TestAssembly.GenericService", null), new("TestAssembly", "TestAssembly.GenericServiceB", typeof(global::TestAssembly.GenericServiceB)), new("TestAssembly", "TestAssembly.IGenericService`1", typeof(global::TestAssembly.IGenericService<>)), new("TestAssembly", "TestAssembly.IOther", typeof(global::TestAssembly.IOther)), new("TestAssembly", "TestAssembly.IRequestHandler`2", typeof(global::TestAssembly.IRequestHandler<, >)), new("TestAssembly", "TestAssembly.IRequest`1", typeof(global::TestAssembly.IRequest<>)), new("TestAssembly", "TestAssembly.IService", typeof(global::TestAssembly.IService)), new("TestAssembly", "TestAssembly.IServiceB", typeof(global::TestAssembly.IServiceB)), new("TestAssembly", "TestAssembly.IValidator", typeof(global::TestAssembly.IValidator)), new("TestAssembly", "TestAssembly.IValidator`1", typeof(global::TestAssembly.IValidator<>)), new("TestAssembly", "TestAssembly.Nested", typeof(global::TestAssembly.Nested)), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", typeof(global::TestAssembly.Nested.GenericServiceA)), new("TestAssembly", "TestAssembly.Nested+MyRecord", null), new("TestAssembly", "TestAssembly.Nested+ServiceA", typeof(global::TestAssembly.Nested.ServiceA)), new("TestAssembly", "TestAssembly.Nested+Validator", null), new("TestAssembly", "TestAssembly.Request", null), new("TestAssembly", "TestAssembly.RequestHandler", null), new("TestAssembly", "TestAssembly.Response", null), new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)), new("TestAssembly", "TestAssembly.ServiceB", null) }),
        new(ScannerExpressionKind.Reflection, "{scrubbed}"),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 262, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableTo<IServiceB>(), false)\n                .AsSelf()\n                .AsImplementedInterfaces()\n                .WithScopedLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 268, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableTo<IService>(), false)\n                .AsSelf()\n                .AsImplementedInterfaces()\n                .WithSingletonLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+ServiceA", typeof(global::TestAssembly.Nested.ServiceA)), new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)), new("TestAssembly", "TestAssembly.ServiceB", null) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 274, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableTo<IService>())\n                .As<IService>()\n                .WithScopedLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+ServiceA", typeof(global::TestAssembly.Nested.ServiceA)), new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)), new("TestAssembly", "TestAssembly.ServiceB", null) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 279, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableTo<IService>())\n                .AsSelf()\n                .AsImplementedInterfaces()\n                .WithSingletonLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+ServiceA", typeof(global::TestAssembly.Nested.ServiceA)), new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)), new("TestAssembly", "TestAssembly.ServiceB", null) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 285, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableTo<IService>())\n                .AsSelf()\n                .AsImplementedInterfaces()\n                .WithScopedLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+ServiceA", typeof(global::TestAssembly.Nested.ServiceA)), new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)), new("TestAssembly", "TestAssembly.ServiceB", null) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 291, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableTo(typeof(IGenericService<>)))\n                .AsSelfWithInterfaces()\n                .WithScopedLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.GenericService", null), new("TestAssembly", "TestAssembly.GenericServiceB", typeof(global::TestAssembly.GenericServiceB)), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", typeof(global::TestAssembly.Nested.GenericServiceA)) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 296, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableTo(typeof(IGenericService<>)))\n                .AsSelf()\n                .AsImplementedInterfaces()\n                .WithScopedLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.GenericService", null), new("TestAssembly", "TestAssembly.GenericServiceB", typeof(global::TestAssembly.GenericServiceB)), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", typeof(global::TestAssembly.Nested.GenericServiceA)) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 302, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableTo(typeof(IRequestHandler<,>)))\n                .AsImplementedInterfaces()\n                .WithSingletonLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.RequestHandler", null) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 307, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableTo<IService>().AssignableTo<IServiceB>())\n                .AsSelf()\n                .AsImplementedInterfaces()\n                .WithScopedLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 313, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableToAny(typeof(IService), typeof(IServiceB)))\n                .AsSelf()\n                .AsImplementedInterfaces()\n                .WithScopedLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+ServiceA", typeof(global::TestAssembly.Nested.ServiceA)), new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)), new("TestAssembly", "TestAssembly.ServiceB", null) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 319, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableToAny(typeof(IService), typeof(IServiceB)))\n                .AsSelf()\n                .AsImplementedInterfaces(z => z.AssignableTo<IServiceB>())\n                .WithScopedLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+ServiceA", typeof(global::TestAssembly.Nested.ServiceA)), new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)), new("TestAssembly", "TestAssembly.ServiceB", null) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 325, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableToAny(typeof(IOther)))\n                .AsSelf()\n                .AsImplementedInterfaces(z => z.AssignableTo(typeof(IGenericService<>)))\n                .WithScopedLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.GenericService", null), new("TestAssembly", "TestAssembly.GenericServiceB", typeof(global::TestAssembly.GenericServiceB)), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", typeof(global::TestAssembly.Nested.GenericServiceA)) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 331, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableToAny(typeof(IValidator)))\n                .AsImplementedInterfaces(z => z.AssignableTo(typeof(IValidator<>)))\n                .WithScopedLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+Validator", null) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 336, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableToAny(typeof(IService)))\n                .As<IService>()\n                .WithScopedLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.Nested+ServiceA", typeof(global::TestAssembly.Nested.ServiceA)), new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)), new("TestAssembly", "TestAssembly.ServiceB", null) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 341, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableToAny(typeof(IOther)))\n                .AsSelf()\n                .As(typeof(IGenericService<>))\n                .WithScopedLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.GenericService", null), new("TestAssembly", "TestAssembly.GenericServiceB", typeof(global::TestAssembly.GenericServiceB)), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", typeof(global::TestAssembly.Nested.GenericServiceA)) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 347, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.AssignableToAny(typeof(IOther)))\n                .As(typeof(IGenericService<>))\n                .WithScopedLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.GenericService", null), new("TestAssembly", "TestAssembly.GenericServiceB", typeof(global::TestAssembly.GenericServiceB)), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", typeof(global::TestAssembly.Nested.GenericServiceA)) }),
        new(ScannerExpressionKind.ServiceDescriptor, "Input0.cs", 366, "z => z\n                .FromAssemblies()\n                .AddClasses(x => x.InNamespaces(\"TestAssembly\"))\n                .AsSelf()\n                .AsImplementedInterfaces()\n                .WithScopedLifetime()", new ScanReportAssembly[] { }, new ScanReportType[] { new("TestAssembly", "TestAssembly.GenericService", null), new("TestAssembly", "TestAssembly.GenericServiceB", typeof(global::TestAssembly.GenericServiceB)), new("TestAssembly", "TestAssembly.Nested+GenericServiceA", typeof(global::TestAssembly.Nested.GenericServiceA)), new("TestAssembly", "TestAssembly.Nested+MyRecord", null), new("TestAssembly", "TestAssembly.Nested+ServiceA", typeof(global::TestAssembly.Nested.ServiceA)), new("TestAssembly", "TestAssembly.Nested+Validator", null), new("TestAssembly", "TestAssembly.Request", null), new("TestAssembly", "TestAssembly.RequestHandler", null), new("TestAssembly", "TestAssembly.Response", null), new("TestAssembly", "TestAssembly.Service", typeof(global::TestAssembly.Service)), new("TestAssembly", "TestAssembly.ServiceB", null) }),
    };

    public const string MermaidDiagram = @"flowchart TD
    F0[Input0.cs:16] --> E0{Assembly}
    E0 --> E0A0[OtherProject]
    E0 --> E0A1[Specular]
    E0 --> E0A2[System.ComponentModel]
    E0 --> E0A3[TestAssembly]
    E0 --> E0A4[TestProject]
    F1[Input0.cs:17] --> E1{Assembly}
    E1 --> E1A0[OtherProject]
    E1 --> E1A1[Specular]
    E1 --> E1A2[System.ComponentModel]
    E1 --> E1A3[TestAssembly]
    E1 --> E1A4[TestProject]
    F2[Input0.cs:18] --> E2{Assembly}
    E2 --> E2A0[OtherProject]
    E2 --> E2A1[Specular]
    E2 --> E2A2[System.ComponentModel]
    E2 --> E2A3[TestAssembly]
    E2 --> E2A4[TestProject]
    F3[Input0.cs:19] --> E3{Assembly}
    E3 --> E3A0[OtherProject]
    F4[Input0.cs:20] --> E4{Assembly}
    E4 --> E4A0[OtherProject]
    E4 --> E4A1[TestProject]
    F5[Input0.cs:21] --> E5{Assembly}
    E5 --> E5A0[OtherProject]
    E5 --> E5A1[TestProject]
    F6[Input0.cs:22] --> E6{Reflection}
    E6 --> E6T0[Specular.Abstractions.IReflectionAssemblySelector]
    E6 --> E6T1[Specular.Abstractions.IReflectionTypeSelector]
    E6 --> E6T2[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E6 --> E6T3[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E6 --> E6T4[Specular.Abstractions.IServiceLifetimeSelector]
    E6 --> E6T5[Specular.Abstractions.IServiceTypeSelector]
    E6 --> E6T6[Specular.Abstractions.ITypeFilter]
    E6 --> E6T7[Specular.Abstractions.TypeInfoFilter]
    E6 --> E6T8[Specular.Abstractions.TypeKindFilter]
    E6 --> E6T9[TestAssembly.IGenericService`1]
    E6 --> E6T10[TestAssembly.IOther]
    E6 --> E6T11[TestAssembly.IRequestHandler`2]
    E6 --> E6T12[TestAssembly.IRequest`1]
    E6 --> E6T13[TestAssembly.IService]
    E6 --> E6T14[TestAssembly.IServiceB]
    E6 --> E6T15[TestAssembly.IValidator]
    E6 --> E6T16[TestAssembly.IValidator`1]
    F7[Input0.cs:32] --> E7{Reflection}
    E7 --> E7T0[Specular.Abstractions.IReflectionAssemblySelector]
    E7 --> E7T1[Specular.Abstractions.IReflectionTypeSelector]
    E7 --> E7T2[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E7 --> E7T3[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E7 --> E7T4[Specular.Abstractions.IServiceLifetimeSelector]
    E7 --> E7T5[Specular.Abstractions.IServiceTypeSelector]
    E7 --> E7T6[Specular.Abstractions.ITypeFilter]
    E7 --> E7T7[TestAssembly.IGenericService`1]
    E7 --> E7T8[TestAssembly.IOther]
    E7 --> E7T9[TestAssembly.IRequestHandler`2]
    E7 --> E7T10[TestAssembly.IRequest`1]
    E7 --> E7T11[TestAssembly.IService]
    E7 --> E7T12[TestAssembly.IServiceB]
    E7 --> E7T13[TestAssembly.IValidator]
    E7 --> E7T14[TestAssembly.IValidator`1]
    F8[Input0.cs:42] --> E8{Reflection}
    E8 --> E8T0[Program]
    E8 --> E8T1[MyAssembly]
    E8 --> E8T2[MyAssembly+Info]
    E8 --> E8T3[MyAssembly+Metadata]
    E8 --> E8T4[MyAssembly+Project]
    E8 --> E8T5[Specular.Abstractions.ExcludeFromSpecularAttribute]
    E8 --> E8T6[Specular.Abstractions.SpecularHashAttribute]
    E8 --> E8T7[Specular.Abstractions.TypeInfoFilter]
    E8 --> E8T8[Specular.Abstractions.TypeKindFilter]
    E8 --> E8T9[Specular.RegistrationLifetimeAttribute]
    E8 --> E8T10[Specular.ServiceRegistrationAttribute]
    E8 --> E8T11[Specular.ServiceRegistrationAttribute`1]
    E8 --> E8T12[Specular.ServiceRegistrationAttribute`2]
    E8 --> E8T13[Specular.ServiceRegistrationAttribute`3]
    E8 --> E8T14[Specular.ServiceRegistrationAttribute`4]
    E8 --> E8T15[Specular.ServiceRegistrationAttribute`5]
    E8 --> E8T16[Specular.ServiceRegistrationAttribute`6]
    E8 --> E8T17[Specular.ServiceRegistrationAttribute`7]
    E8 --> E8T18[Specular.ServiceRegistrationAttribute`8]
    E8 --> E8T19[Specular.SpecularProviderServiceCollectionExtensions]
    E8 --> E8T20[Specular.SpecularSupport]
    E8 --> E8T21[MyAssembly]
    E8 --> E8T22[MyAssembly+Info]
    E8 --> E8T23[MyAssembly+Metadata]
    E8 --> E8T24[MyAssembly+Project]
    E8 --> E8T25[TestAssembly.GenericService]
    E8 --> E8T26[TestAssembly.GenericServiceB]
    E8 --> E8T27[TestAssembly.Nested]
    E8 --> E8T28[TestAssembly.Nested+GenericServiceA]
    E8 --> E8T29[TestAssembly.Nested+MyRecord]
    E8 --> E8T30[TestAssembly.Nested+ServiceA]
    E8 --> E8T31[TestAssembly.Nested+Validator]
    E8 --> E8T32[TestAssembly.Request]
    E8 --> E8T33[TestAssembly.RequestHandler]
    E8 --> E8T34[TestAssembly.Response]
    E8 --> E8T35[TestAssembly.Service]
    E8 --> E8T36[TestAssembly.ServiceB]
    E8 --> E8T37[Microsoft.CodeAnalysis.EmbeddedAttribute]
    F9[Input0.cs:52] --> E9{Reflection}
    E9 --> E9T0[Specular.Abstractions.IReflectionAssemblySelector]
    E9 --> E9T1[Specular.Abstractions.IReflectionTypeSelector]
    E9 --> E9T2[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E9 --> E9T3[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E9 --> E9T4[Specular.Abstractions.IServiceLifetimeSelector]
    E9 --> E9T5[Specular.Abstractions.IServiceTypeSelector]
    E9 --> E9T6[Specular.Abstractions.ITypeFilter]
    E9 --> E9T7[TestAssembly.IGenericService`1]
    E9 --> E9T8[TestAssembly.IOther]
    E9 --> E9T9[TestAssembly.IRequestHandler`2]
    E9 --> E9T10[TestAssembly.IRequest`1]
    E9 --> E9T11[TestAssembly.IService]
    E9 --> E9T12[TestAssembly.IServiceB]
    E9 --> E9T13[TestAssembly.IValidator]
    E9 --> E9T14[TestAssembly.IValidator`1]
    F10[Input0.cs:62] --> E10{Reflection}
    E10 --> E10T0[Specular.Abstractions.ExcludeFromSpecularAttribute]
    E10 --> E10T1[Specular.Abstractions.IReflectionAssemblySelector]
    E10 --> E10T2[Specular.Abstractions.IReflectionTypeSelector]
    E10 --> E10T3[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E10 --> E10T4[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E10 --> E10T5[Specular.Abstractions.IServiceLifetimeSelector]
    E10 --> E10T6[Specular.Abstractions.IServiceTypeSelector]
    E10 --> E10T7[Specular.Abstractions.ITypeFilter]
    E10 --> E10T8[Specular.Abstractions.SpecularHashAttribute]
    E10 --> E10T9[Specular.Abstractions.TypeInfoFilter]
    E10 --> E10T10[Specular.Abstractions.TypeKindFilter]
    E10 --> E10T11[Specular.RegistrationLifetimeAttribute]
    E10 --> E10T12[Specular.ServiceRegistrationAttribute]
    E10 --> E10T13[Specular.ServiceRegistrationAttribute`1]
    E10 --> E10T14[Specular.ServiceRegistrationAttribute`2]
    E10 --> E10T15[Specular.ServiceRegistrationAttribute`3]
    E10 --> E10T16[Specular.ServiceRegistrationAttribute`4]
    E10 --> E10T17[Specular.ServiceRegistrationAttribute`5]
    E10 --> E10T18[Specular.ServiceRegistrationAttribute`6]
    E10 --> E10T19[Specular.ServiceRegistrationAttribute`7]
    E10 --> E10T20[Specular.ServiceRegistrationAttribute`8]
    E10 --> E10T21[Specular.SpecularProviderServiceCollectionExtensions]
    E10 --> E10T22[Specular.SpecularSupport]
    E10 --> E10T23[TestAssembly.GenericServiceB]
    E10 --> E10T24[TestAssembly.IGenericService`1]
    E10 --> E10T25[TestAssembly.IOther]
    E10 --> E10T26[TestAssembly.IRequestHandler`2]
    E10 --> E10T27[TestAssembly.IRequest`1]
    E10 --> E10T28[TestAssembly.IService]
    E10 --> E10T29[TestAssembly.IServiceB]
    E10 --> E10T30[TestAssembly.IValidator]
    E10 --> E10T31[TestAssembly.IValidator`1]
    E10 --> E10T32[TestAssembly.Nested]
    E10 --> E10T33[TestAssembly.Nested+GenericServiceA]
    E10 --> E10T34[TestAssembly.Nested+ServiceA]
    E10 --> E10T35[TestAssembly.Service]
    F11[Input0.cs:72] --> E11{Reflection}
    E11 --> E11T0[Specular.Abstractions.TypeInfoFilter]
    E11 --> E11T1[Specular.Abstractions.TypeKindFilter]
    F12[Input0.cs:82] --> E12{Reflection}
    E12 --> E12T0[Specular.Abstractions.SpecularHashAttribute]
    E12 --> E12T1[Specular.Abstractions.TypeInfoFilter]
    E12 --> E12T2[Specular.Abstractions.TypeKindFilter]
    E12 --> E12T3[Specular.ServiceRegistrationAttribute`1]
    E12 --> E12T4[Specular.ServiceRegistrationAttribute`2]
    E12 --> E12T5[Specular.ServiceRegistrationAttribute`3]
    E12 --> E12T6[Specular.ServiceRegistrationAttribute`4]
    E12 --> E12T7[Specular.ServiceRegistrationAttribute`5]
    E12 --> E12T8[Specular.ServiceRegistrationAttribute`6]
    E12 --> E12T9[Specular.ServiceRegistrationAttribute`7]
    E12 --> E12T10[Specular.ServiceRegistrationAttribute`8]
    E12 --> E12T11[Microsoft.CodeAnalysis.EmbeddedAttribute]
    F13[Input0.cs:92] --> E13{Reflection}
    E13 --> E13T0[MyAssembly]
    E13 --> E13T1[MyAssembly+Info]
    E13 --> E13T2[MyAssembly+Metadata]
    E13 --> E13T3[MyAssembly+Project]
    E13 --> E13T4[Specular.SpecularProviderServiceCollectionExtensions]
    E13 --> E13T5[Specular.SpecularSupport]
    E13 --> E13T6[MyAssembly]
    E13 --> E13T7[MyAssembly+Info]
    E13 --> E13T8[MyAssembly+Metadata]
    E13 --> E13T9[MyAssembly+Project]
    E13 --> E13T10[TestAssembly.Nested]
    F14[Input0.cs:102] --> E14{Reflection}
    E14 --> E14T0[Program]
    E14 --> E14T1[Specular.Abstractions.ExcludeFromSpecularAttribute]
    E14 --> E14T2[Specular.Abstractions.IReflectionAssemblySelector]
    E14 --> E14T3[Specular.Abstractions.IReflectionTypeSelector]
    E14 --> E14T4[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E14 --> E14T5[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E14 --> E14T6[Specular.Abstractions.IServiceLifetimeSelector]
    E14 --> E14T7[Specular.Abstractions.IServiceTypeSelector]
    E14 --> E14T8[Specular.Abstractions.ITypeFilter]
    E14 --> E14T9[Specular.Abstractions.SpecularHashAttribute]
    E14 --> E14T10[Specular.Abstractions.TypeInfoFilter]
    E14 --> E14T11[Specular.Abstractions.TypeKindFilter]
    E14 --> E14T12[Specular.RegistrationLifetimeAttribute]
    E14 --> E14T13[Specular.ServiceRegistrationAttribute]
    E14 --> E14T14[Specular.ServiceRegistrationAttribute`1]
    E14 --> E14T15[Specular.ServiceRegistrationAttribute`2]
    E14 --> E14T16[Specular.ServiceRegistrationAttribute`3]
    E14 --> E14T17[Specular.ServiceRegistrationAttribute`4]
    E14 --> E14T18[Specular.ServiceRegistrationAttribute`5]
    E14 --> E14T19[Specular.ServiceRegistrationAttribute`6]
    E14 --> E14T20[Specular.ServiceRegistrationAttribute`7]
    E14 --> E14T21[Specular.ServiceRegistrationAttribute`8]
    E14 --> E14T22[TestAssembly.GenericService]
    E14 --> E14T23[TestAssembly.GenericServiceB]
    E14 --> E14T24[TestAssembly.IGenericService`1]
    E14 --> E14T25[TestAssembly.IOther]
    E14 --> E14T26[TestAssembly.IRequestHandler`2]
    E14 --> E14T27[TestAssembly.IRequest`1]
    E14 --> E14T28[TestAssembly.IService]
    E14 --> E14T29[TestAssembly.IServiceB]
    E14 --> E14T30[TestAssembly.IValidator]
    E14 --> E14T31[TestAssembly.IValidator`1]
    E14 --> E14T32[TestAssembly.Nested+GenericServiceA]
    E14 --> E14T33[TestAssembly.Nested+MyRecord]
    E14 --> E14T34[TestAssembly.Nested+ServiceA]
    E14 --> E14T35[TestAssembly.Nested+Validator]
    E14 --> E14T36[TestAssembly.Request]
    E14 --> E14T37[TestAssembly.RequestHandler]
    E14 --> E14T38[TestAssembly.Response]
    E14 --> E14T39[TestAssembly.Service]
    E14 --> E14T40[TestAssembly.ServiceB]
    E14 --> E14T41[Microsoft.CodeAnalysis.EmbeddedAttribute]
    F15[Input0.cs:112] --> E15{Reflection}
    E15 --> E15T0[Specular.ServiceRegistrationAttribute`1]
    E15 --> E15T1[Specular.ServiceRegistrationAttribute`2]
    E15 --> E15T2[Specular.ServiceRegistrationAttribute`3]
    E15 --> E15T3[Specular.ServiceRegistrationAttribute`4]
    E15 --> E15T4[Specular.ServiceRegistrationAttribute`5]
    E15 --> E15T5[Specular.ServiceRegistrationAttribute`6]
    E15 --> E15T6[Specular.ServiceRegistrationAttribute`7]
    E15 --> E15T7[Specular.ServiceRegistrationAttribute`8]
    E15 --> E15T8[TestAssembly.IGenericService`1]
    E15 --> E15T9[TestAssembly.IRequestHandler`2]
    E15 --> E15T10[TestAssembly.IRequest`1]
    E15 --> E15T11[TestAssembly.IValidator`1]
    F16[Input0.cs:122] --> E16{Reflection}
    E16 --> E16T0[Program]
    E16 --> E16T1[MyAssembly]
    E16 --> E16T2[MyAssembly+Info]
    E16 --> E16T3[MyAssembly+Metadata]
    E16 --> E16T4[MyAssembly+Project]
    E16 --> E16T5[Specular.Abstractions.ExcludeFromSpecularAttribute]
    E16 --> E16T6[Specular.Abstractions.SpecularHashAttribute]
    E16 --> E16T7[Specular.Abstractions.TypeInfoFilter]
    E16 --> E16T8[Specular.Abstractions.TypeKindFilter]
    E16 --> E16T9[Specular.RegistrationLifetimeAttribute]
    E16 --> E16T10[Specular.ServiceRegistrationAttribute]
    E16 --> E16T11[Specular.ServiceRegistrationAttribute`1]
    E16 --> E16T12[Specular.ServiceRegistrationAttribute`2]
    E16 --> E16T13[Specular.ServiceRegistrationAttribute`3]
    E16 --> E16T14[Specular.ServiceRegistrationAttribute`4]
    E16 --> E16T15[Specular.ServiceRegistrationAttribute`5]
    E16 --> E16T16[Specular.ServiceRegistrationAttribute`6]
    E16 --> E16T17[Specular.ServiceRegistrationAttribute`7]
    E16 --> E16T18[Specular.ServiceRegistrationAttribute`8]
    E16 --> E16T19[Specular.SpecularProviderServiceCollectionExtensions]
    E16 --> E16T20[Specular.SpecularSupport]
    E16 --> E16T21[MyAssembly]
    E16 --> E16T22[MyAssembly+Info]
    E16 --> E16T23[MyAssembly+Metadata]
    E16 --> E16T24[MyAssembly+Project]
    E16 --> E16T25[TestAssembly.GenericService]
    E16 --> E16T26[TestAssembly.GenericServiceB]
    E16 --> E16T27[TestAssembly.Nested]
    E16 --> E16T28[TestAssembly.Nested+GenericServiceA]
    E16 --> E16T29[TestAssembly.Nested+MyRecord]
    E16 --> E16T30[TestAssembly.Nested+ServiceA]
    E16 --> E16T31[TestAssembly.Nested+Validator]
    E16 --> E16T32[TestAssembly.Request]
    E16 --> E16T33[TestAssembly.RequestHandler]
    E16 --> E16T34[TestAssembly.Response]
    E16 --> E16T35[TestAssembly.Service]
    E16 --> E16T36[TestAssembly.ServiceB]
    E16 --> E16T37[Microsoft.CodeAnalysis.EmbeddedAttribute]
    F17[Input0.cs:132] --> E17{Reflection}
    E17 --> E17T0[Program]
    E17 --> E17T1[MyAssembly]
    E17 --> E17T2[MyAssembly+Info]
    E17 --> E17T3[MyAssembly+Metadata]
    E17 --> E17T4[MyAssembly+Project]
    E17 --> E17T5[MyAssembly]
    E17 --> E17T6[MyAssembly+Info]
    E17 --> E17T7[MyAssembly+Metadata]
    E17 --> E17T8[MyAssembly+Project]
    E17 --> E17T9[TestAssembly.GenericService]
    E17 --> E17T10[TestAssembly.Nested+MyRecord]
    E17 --> E17T11[TestAssembly.Nested+Validator]
    E17 --> E17T12[TestAssembly.Request]
    E17 --> E17T13[TestAssembly.RequestHandler]
    E17 --> E17T14[TestAssembly.Response]
    E17 --> E17T15[TestAssembly.ServiceB]
    F18[Input0.cs:147] --> E18{Reflection}
    E18 --> E18T0[Program]
    E18 --> E18T1[MyAssembly]
    E18 --> E18T2[MyAssembly+Info]
    E18 --> E18T3[MyAssembly+Metadata]
    E18 --> E18T4[MyAssembly+Project]
    E18 --> E18T5[Specular.Abstractions.IReflectionAssemblySelector]
    E18 --> E18T6[Specular.Abstractions.IReflectionTypeSelector]
    E18 --> E18T7[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E18 --> E18T8[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E18 --> E18T9[Specular.Abstractions.IServiceLifetimeSelector]
    E18 --> E18T10[Specular.Abstractions.IServiceTypeSelector]
    E18 --> E18T11[Specular.Abstractions.ITypeFilter]
    E18 --> E18T12[Specular.SpecularProviderServiceCollectionExtensions]
    E18 --> E18T13[Specular.SpecularSupport]
    E18 --> E18T14[MyAssembly]
    E18 --> E18T15[MyAssembly+Info]
    E18 --> E18T16[MyAssembly+Metadata]
    E18 --> E18T17[MyAssembly+Project]
    E18 --> E18T18[TestAssembly.GenericService]
    E18 --> E18T19[TestAssembly.GenericServiceB]
    E18 --> E18T20[TestAssembly.IGenericService`1]
    E18 --> E18T21[TestAssembly.IOther]
    E18 --> E18T22[TestAssembly.IRequestHandler`2]
    E18 --> E18T23[TestAssembly.IRequest`1]
    E18 --> E18T24[TestAssembly.IService]
    E18 --> E18T25[TestAssembly.IServiceB]
    E18 --> E18T26[TestAssembly.IValidator]
    E18 --> E18T27[TestAssembly.IValidator`1]
    E18 --> E18T28[TestAssembly.Nested]
    E18 --> E18T29[TestAssembly.Nested+GenericServiceA]
    E18 --> E18T30[TestAssembly.Nested+MyRecord]
    E18 --> E18T31[TestAssembly.Nested+ServiceA]
    E18 --> E18T32[TestAssembly.Nested+Validator]
    E18 --> E18T33[TestAssembly.Request]
    E18 --> E18T34[TestAssembly.RequestHandler]
    E18 --> E18T35[TestAssembly.Response]
    E18 --> E18T36[TestAssembly.Service]
    E18 --> E18T37[TestAssembly.ServiceB]
    F19[Input0.cs:158] --> E19{Reflection}
    E19 --> E19T0[Program]
    E19 --> E19T1[MyAssembly]
    E19 --> E19T2[MyAssembly+Info]
    E19 --> E19T3[MyAssembly+Metadata]
    E19 --> E19T4[MyAssembly+Project]
    E19 --> E19T5[Specular.Abstractions.IReflectionAssemblySelector]
    E19 --> E19T6[Specular.Abstractions.IReflectionTypeSelector]
    E19 --> E19T7[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E19 --> E19T8[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E19 --> E19T9[Specular.Abstractions.IServiceLifetimeSelector]
    E19 --> E19T10[Specular.Abstractions.IServiceTypeSelector]
    E19 --> E19T11[Specular.Abstractions.ITypeFilter]
    E19 --> E19T12[Specular.SpecularProviderServiceCollectionExtensions]
    E19 --> E19T13[Specular.SpecularSupport]
    E19 --> E19T14[MyAssembly]
    E19 --> E19T15[MyAssembly+Info]
    E19 --> E19T16[MyAssembly+Metadata]
    E19 --> E19T17[MyAssembly+Project]
    E19 --> E19T18[TestAssembly.GenericService]
    E19 --> E19T19[TestAssembly.GenericServiceB]
    E19 --> E19T20[TestAssembly.IGenericService`1]
    E19 --> E19T21[TestAssembly.IOther]
    E19 --> E19T22[TestAssembly.IRequestHandler`2]
    E19 --> E19T23[TestAssembly.IRequest`1]
    E19 --> E19T24[TestAssembly.IService]
    E19 --> E19T25[TestAssembly.IServiceB]
    E19 --> E19T26[TestAssembly.IValidator]
    E19 --> E19T27[TestAssembly.IValidator`1]
    E19 --> E19T28[TestAssembly.Nested]
    E19 --> E19T29[TestAssembly.Nested+GenericServiceA]
    E19 --> E19T30[TestAssembly.Nested+MyRecord]
    E19 --> E19T31[TestAssembly.Nested+ServiceA]
    E19 --> E19T32[TestAssembly.Nested+Validator]
    E19 --> E19T33[TestAssembly.Request]
    E19 --> E19T34[TestAssembly.RequestHandler]
    E19 --> E19T35[TestAssembly.Response]
    E19 --> E19T36[TestAssembly.Service]
    E19 --> E19T37[TestAssembly.ServiceB]
    F20[Input0.cs:169] --> E20{Reflection}
    E20 --> E20T0[Program]
    E20 --> E20T1[MyAssembly]
    E20 --> E20T2[MyAssembly+Info]
    E20 --> E20T3[MyAssembly+Metadata]
    E20 --> E20T4[MyAssembly+Project]
    E20 --> E20T5[Specular.Abstractions.IReflectionAssemblySelector]
    E20 --> E20T6[Specular.Abstractions.IReflectionTypeSelector]
    E20 --> E20T7[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E20 --> E20T8[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E20 --> E20T9[Specular.Abstractions.IServiceLifetimeSelector]
    E20 --> E20T10[Specular.Abstractions.IServiceTypeSelector]
    E20 --> E20T11[Specular.Abstractions.ITypeFilter]
    E20 --> E20T12[Specular.Abstractions.TypeInfoFilter]
    E20 --> E20T13[Specular.Abstractions.TypeKindFilter]
    E20 --> E20T14[Specular.SpecularProviderServiceCollectionExtensions]
    E20 --> E20T15[Specular.SpecularSupport]
    E20 --> E20T16[MyAssembly]
    E20 --> E20T17[MyAssembly+Info]
    E20 --> E20T18[MyAssembly+Metadata]
    E20 --> E20T19[MyAssembly+Project]
    E20 --> E20T20[TestAssembly.GenericService]
    E20 --> E20T21[TestAssembly.GenericServiceB]
    E20 --> E20T22[TestAssembly.IOther]
    E20 --> E20T23[TestAssembly.IService]
    E20 --> E20T24[TestAssembly.IServiceB]
    E20 --> E20T25[TestAssembly.IValidator]
    E20 --> E20T26[TestAssembly.Nested]
    E20 --> E20T27[TestAssembly.Nested+GenericServiceA]
    E20 --> E20T28[TestAssembly.Nested+MyRecord]
    E20 --> E20T29[TestAssembly.Nested+ServiceA]
    E20 --> E20T30[TestAssembly.Nested+Validator]
    E20 --> E20T31[TestAssembly.Request]
    E20 --> E20T32[TestAssembly.RequestHandler]
    E20 --> E20T33[TestAssembly.Response]
    E20 --> E20T34[TestAssembly.Service]
    E20 --> E20T35[TestAssembly.ServiceB]
    F21[Input0.cs:180] --> E21{Reflection}
    E21 --> E21T0[Specular.SpecularSupport]
    F22[Input0.cs:190] --> E22{Reflection}
    E22 --> E22T0[Specular.SpecularSupport]
    F23[Input0.cs:200] --> E23{Reflection}
    E23 --> E23T0[Program]
    E23 --> E23T1[MyAssembly]
    E23 --> E23T2[MyAssembly+Info]
    E23 --> E23T3[MyAssembly+Metadata]
    E23 --> E23T4[MyAssembly+Project]
    E23 --> E23T5[Specular.Abstractions.IReflectionAssemblySelector]
    E23 --> E23T6[Specular.Abstractions.IReflectionTypeSelector]
    E23 --> E23T7[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E23 --> E23T8[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E23 --> E23T9[Specular.Abstractions.IServiceLifetimeSelector]
    E23 --> E23T10[Specular.Abstractions.IServiceTypeSelector]
    E23 --> E23T11[Specular.Abstractions.ITypeFilter]
    E23 --> E23T12[Specular.Abstractions.TypeInfoFilter]
    E23 --> E23T13[Specular.Abstractions.TypeKindFilter]
    E23 --> E23T14[Specular.SpecularProviderServiceCollectionExtensions]
    E23 --> E23T15[MyAssembly]
    E23 --> E23T16[MyAssembly+Info]
    E23 --> E23T17[MyAssembly+Metadata]
    E23 --> E23T18[MyAssembly+Project]
    E23 --> E23T19[TestAssembly.GenericService]
    E23 --> E23T20[TestAssembly.GenericServiceB]
    E23 --> E23T21[TestAssembly.IGenericService`1]
    E23 --> E23T22[TestAssembly.IOther]
    E23 --> E23T23[TestAssembly.IRequestHandler`2]
    E23 --> E23T24[TestAssembly.IRequest`1]
    E23 --> E23T25[TestAssembly.IService]
    E23 --> E23T26[TestAssembly.IServiceB]
    E23 --> E23T27[TestAssembly.IValidator]
    E23 --> E23T28[TestAssembly.IValidator`1]
    E23 --> E23T29[TestAssembly.Nested]
    E23 --> E23T30[TestAssembly.Nested+GenericServiceA]
    E23 --> E23T31[TestAssembly.Nested+MyRecord]
    E23 --> E23T32[TestAssembly.Nested+ServiceA]
    E23 --> E23T33[TestAssembly.Nested+Validator]
    E23 --> E23T34[TestAssembly.Request]
    E23 --> E23T35[TestAssembly.RequestHandler]
    E23 --> E23T36[TestAssembly.Response]
    E23 --> E23T37[TestAssembly.Service]
    E23 --> E23T38[TestAssembly.ServiceB]
    F24[Input0.cs:211] --> E24{Reflection}
    E24 --> E24T0[Program]
    E24 --> E24T1[MyAssembly]
    E24 --> E24T2[MyAssembly+Info]
    E24 --> E24T3[MyAssembly+Metadata]
    E24 --> E24T4[MyAssembly+Project]
    E24 --> E24T5[Specular.Abstractions.IReflectionAssemblySelector]
    E24 --> E24T6[Specular.Abstractions.IReflectionTypeSelector]
    E24 --> E24T7[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E24 --> E24T8[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E24 --> E24T9[Specular.Abstractions.IServiceLifetimeSelector]
    E24 --> E24T10[Specular.Abstractions.IServiceTypeSelector]
    E24 --> E24T11[Specular.Abstractions.ITypeFilter]
    E24 --> E24T12[Specular.Abstractions.TypeInfoFilter]
    E24 --> E24T13[Specular.Abstractions.TypeKindFilter]
    E24 --> E24T14[Specular.SpecularProviderServiceCollectionExtensions]
    E24 --> E24T15[MyAssembly]
    E24 --> E24T16[MyAssembly+Info]
    E24 --> E24T17[MyAssembly+Metadata]
    E24 --> E24T18[MyAssembly+Project]
    E24 --> E24T19[TestAssembly.GenericService]
    E24 --> E24T20[TestAssembly.GenericServiceB]
    E24 --> E24T21[TestAssembly.IGenericService`1]
    E24 --> E24T22[TestAssembly.IOther]
    E24 --> E24T23[TestAssembly.IRequestHandler`2]
    E24 --> E24T24[TestAssembly.IRequest`1]
    E24 --> E24T25[TestAssembly.IService]
    E24 --> E24T26[TestAssembly.IServiceB]
    E24 --> E24T27[TestAssembly.IValidator]
    E24 --> E24T28[TestAssembly.IValidator`1]
    E24 --> E24T29[TestAssembly.Nested]
    E24 --> E24T30[TestAssembly.Nested+GenericServiceA]
    E24 --> E24T31[TestAssembly.Nested+MyRecord]
    E24 --> E24T32[TestAssembly.Nested+ServiceA]
    E24 --> E24T33[TestAssembly.Nested+Validator]
    E24 --> E24T34[TestAssembly.Request]
    E24 --> E24T35[TestAssembly.RequestHandler]
    E24 --> E24T36[TestAssembly.Response]
    E24 --> E24T37[TestAssembly.Service]
    E24 --> E24T38[TestAssembly.ServiceB]
    F25[Input0.cs:252] --> E25{Reflection}
    E25 --> E25T0[Specular.Abstractions.ExcludeFromSpecularAttribute]
    E25 --> E25T1[Specular.Abstractions.IReflectionAssemblySelector]
    E25 --> E25T2[Specular.Abstractions.IReflectionTypeSelector]
    E25 --> E25T3[Specular.Abstractions.IServiceDescriptorAssemblySelector]
    E25 --> E25T4[Specular.Abstractions.IServiceDescriptorTypeSelector]
    E25 --> E25T5[Specular.Abstractions.IServiceLifetimeSelector]
    E25 --> E25T6[Specular.Abstractions.IServiceTypeSelector]
    E25 --> E25T7[Specular.Abstractions.ITypeFilter]
    E25 --> E25T8[Specular.Abstractions.SpecularHashAttribute]
    E25 --> E25T9[Specular.Abstractions.TypeInfoFilter]
    E25 --> E25T10[Specular.Abstractions.TypeKindFilter]
    E25 --> E25T11[Specular.RegistrationLifetimeAttribute]
    E25 --> E25T12[Specular.ServiceRegistrationAttribute]
    E25 --> E25T13[Specular.ServiceRegistrationAttribute`1]
    E25 --> E25T14[Specular.ServiceRegistrationAttribute`2]
    E25 --> E25T15[Specular.ServiceRegistrationAttribute`3]
    E25 --> E25T16[Specular.ServiceRegistrationAttribute`4]
    E25 --> E25T17[Specular.ServiceRegistrationAttribute`5]
    E25 --> E25T18[Specular.ServiceRegistrationAttribute`6]
    E25 --> E25T19[Specular.ServiceRegistrationAttribute`7]
    E25 --> E25T20[Specular.ServiceRegistrationAttribute`8]
    E25 --> E25T21[Specular.SpecularProviderServiceCollectionExtensions]
    E25 --> E25T22[Specular.SpecularSupport]
    E25 --> E25T23[TestAssembly.GenericServiceB]
    E25 --> E25T24[TestAssembly.IGenericService`1]
    E25 --> E25T25[TestAssembly.IOther]
    E25 --> E25T26[TestAssembly.IRequestHandler`2]
    E25 --> E25T27[TestAssembly.IRequest`1]
    E25 --> E25T28[TestAssembly.IService]
    E25 --> E25T29[TestAssembly.IServiceB]
    E25 --> E25T30[TestAssembly.IValidator]
    E25 --> E25T31[TestAssembly.IValidator`1]
    E25 --> E25T32[TestAssembly.Nested]
    E25 --> E25T33[TestAssembly.Nested+GenericServiceA]
    E25 --> E25T34[TestAssembly.Nested+ServiceA]
    E25 --> E25T35[TestAssembly.Service]
    F26[Input0.cs:262] --> E26{ServiceDescriptor}
    E26 --> E26T0[TestAssembly.Service]
    F27[Input0.cs:268] --> E27{ServiceDescriptor}
    E27 --> E27T0[TestAssembly.Nested+ServiceA]
    E27 --> E27T1[TestAssembly.Service]
    E27 --> E27T2[TestAssembly.ServiceB]
    F28[Input0.cs:274] --> E28{ServiceDescriptor}
    E28 --> E28T0[TestAssembly.Nested+ServiceA]
    E28 --> E28T1[TestAssembly.Service]
    E28 --> E28T2[TestAssembly.ServiceB]
    F29[Input0.cs:279] --> E29{ServiceDescriptor}
    E29 --> E29T0[TestAssembly.Nested+ServiceA]
    E29 --> E29T1[TestAssembly.Service]
    E29 --> E29T2[TestAssembly.ServiceB]
    F30[Input0.cs:285] --> E30{ServiceDescriptor}
    E30 --> E30T0[TestAssembly.Nested+ServiceA]
    E30 --> E30T1[TestAssembly.Service]
    E30 --> E30T2[TestAssembly.ServiceB]
    F31[Input0.cs:291] --> E31{ServiceDescriptor}
    E31 --> E31T0[TestAssembly.GenericService]
    E31 --> E31T1[TestAssembly.GenericServiceB]
    E31 --> E31T2[TestAssembly.Nested+GenericServiceA]
    F32[Input0.cs:296] --> E32{ServiceDescriptor}
    E32 --> E32T0[TestAssembly.GenericService]
    E32 --> E32T1[TestAssembly.GenericServiceB]
    E32 --> E32T2[TestAssembly.Nested+GenericServiceA]
    F33[Input0.cs:302] --> E33{ServiceDescriptor}
    E33 --> E33T0[TestAssembly.RequestHandler]
    F34[Input0.cs:307] --> E34{ServiceDescriptor}
    E34 --> E34T0[TestAssembly.Service]
    F35[Input0.cs:313] --> E35{ServiceDescriptor}
    E35 --> E35T0[TestAssembly.Nested+ServiceA]
    E35 --> E35T1[TestAssembly.Service]
    E35 --> E35T2[TestAssembly.ServiceB]
    F36[Input0.cs:319] --> E36{ServiceDescriptor}
    E36 --> E36T0[TestAssembly.Nested+ServiceA]
    E36 --> E36T1[TestAssembly.Service]
    E36 --> E36T2[TestAssembly.ServiceB]
    F37[Input0.cs:325] --> E37{ServiceDescriptor}
    E37 --> E37T0[TestAssembly.GenericService]
    E37 --> E37T1[TestAssembly.GenericServiceB]
    E37 --> E37T2[TestAssembly.Nested+GenericServiceA]
    F38[Input0.cs:331] --> E38{ServiceDescriptor}
    E38 --> E38T0[TestAssembly.Nested+Validator]
    F39[Input0.cs:336] --> E39{ServiceDescriptor}
    E39 --> E39T0[TestAssembly.Nested+ServiceA]
    E39 --> E39T1[TestAssembly.Service]
    E39 --> E39T2[TestAssembly.ServiceB]
    F40[Input0.cs:341] --> E40{ServiceDescriptor}
    E40 --> E40T0[TestAssembly.GenericService]
    E40 --> E40T1[TestAssembly.GenericServiceB]
    E40 --> E40T2[TestAssembly.Nested+GenericServiceA]
    F41[Input0.cs:347] --> E41{ServiceDescriptor}
    E41 --> E41T0[TestAssembly.GenericService]
    E41 --> E41T1[TestAssembly.GenericServiceB]
    E41 --> E41T2[TestAssembly.Nested+GenericServiceA]
    F42[Input0.cs:366] --> E42{ServiceDescriptor}
    E42 --> E42T0[TestAssembly.GenericService]
    E42 --> E42T1[TestAssembly.GenericServiceB]
    E42 --> E42T2[TestAssembly.Nested+GenericServiceA]
    E42 --> E42T3[TestAssembly.Nested+MyRecord]
    E42 --> E42T4[TestAssembly.Nested+ServiceA]
    E42 --> E42T5[TestAssembly.Nested+Validator]
    E42 --> E42T6[TestAssembly.Request]
    E42 --> E42T7[TestAssembly.RequestHandler]
    E42 --> E42T8[TestAssembly.Response]
    E42 --> E42T9[TestAssembly.Service]
    E42 --> E42T10[TestAssembly.ServiceB]
";
}
#nullable restore
