//HintName: Specular.Analyzers/Specular.Analyzers.SpecularProviderGenerator/SpecularScanReport.g.cs
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.Extensions.DependencyInjection;
using Specular;
using Specular.Abstractions;
using Specular.Diagnostics;

[System.CodeDom.Compiler.GeneratedCode("Specular.Analyzers", "version"), System.Runtime.CompilerServices.CompilerGenerated, Microsoft.CodeAnalysis.EmbeddedAttribute, System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal sealed class SpecularScanReport
{
    public static ScanResults GetScanResults() => new(
        []
    , 
        []
    , 
        [
            new("TestProject", "z =>\r\n{\r\n    z.FromAssemblies().AddClasses(x => x.AssignableTo(typeof(IService))).AsSelf().AsImplementedInterfaces().WithScopedLifetime();\r\n}", 
                [
                    new("Microsoft.Extensions.DependencyInjection.Abstractions", 
                        [
                            new(ServiceLifetime.Transient, "global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities+ConstructorInfoEx", "global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities+ConstructorInfoEx"), 
                            new(ServiceLifetime.Transient, "global::Microsoft.Extensions.DependencyInjection.ActivatorUtilitiesConstructorAttribute", "global::Microsoft.Extensions.DependencyInjection.ActivatorUtilitiesConstructorAttribute"), 
                            new(ServiceLifetime.Transient, "global::Microsoft.Extensions.DependencyInjection.FromKeyedServicesAttribute", "global::Microsoft.Extensions.DependencyInjection.FromKeyedServicesAttribute"), 
                            new(ServiceLifetime.Transient, "global::Microsoft.Extensions.DependencyInjection.KeyedService+AnyKeyObj", "global::Microsoft.Extensions.DependencyInjection.KeyedService+AnyKeyObj"), 
                            new(ServiceLifetime.Transient, "global::Microsoft.Extensions.DependencyInjection.ServiceCollection", "global::Microsoft.Extensions.DependencyInjection.ServiceCollection"), 
                            new(ServiceLifetime.Transient, "global::Microsoft.Extensions.DependencyInjection.ServiceCollection+ServiceCollectionDebugView", "global::Microsoft.Extensions.DependencyInjection.ServiceCollection+ServiceCollectionDebugView"), 
                            new(ServiceLifetime.Transient, "global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor", "global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor"), 
                            new(ServiceLifetime.Transient, "global::Microsoft.Extensions.DependencyInjection.ServiceKeyAttribute", "global::Microsoft.Extensions.DependencyInjection.ServiceKeyAttribute")]
                    ), 
                    new("Specular", 
                        [
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspAttributeRoutingAttribute", "global::JetBrains.Annotations.AspAttributeRoutingAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspChildControlTypeAttribute", "global::JetBrains.Annotations.AspChildControlTypeAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspDataFieldAttribute", "global::JetBrains.Annotations.AspDataFieldAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspDataFieldsAttribute", "global::JetBrains.Annotations.AspDataFieldsAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspDefaultRouteValuesAttribute", "global::JetBrains.Annotations.AspDefaultRouteValuesAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMethodPropertyAttribute", "global::JetBrains.Annotations.AspMethodPropertyAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMinimalApiDeclarationAttribute", "global::JetBrains.Annotations.AspMinimalApiDeclarationAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMinimalApiGroupAttribute", "global::JetBrains.Annotations.AspMinimalApiGroupAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMinimalApiHandlerAttribute", "global::JetBrains.Annotations.AspMinimalApiHandlerAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMinimalApiImplicitEndpointDeclarationAttribute", "global::JetBrains.Annotations.AspMinimalApiImplicitEndpointDeclarationAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcActionAttribute", "global::JetBrains.Annotations.AspMvcActionAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcActionSelectorAttribute", "global::JetBrains.Annotations.AspMvcActionSelectorAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcAreaAttribute", "global::JetBrains.Annotations.AspMvcAreaAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcAreaMasterLocationFormatAttribute", "global::JetBrains.Annotations.AspMvcAreaMasterLocationFormatAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcAreaPartialViewLocationFormatAttribute", "global::JetBrains.Annotations.AspMvcAreaPartialViewLocationFormatAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcAreaViewComponentViewLocationFormatAttribute", "global::JetBrains.Annotations.AspMvcAreaViewComponentViewLocationFormatAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcAreaViewLocationFormatAttribute", "global::JetBrains.Annotations.AspMvcAreaViewLocationFormatAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcControllerAttribute", "global::JetBrains.Annotations.AspMvcControllerAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcDisplayTemplateAttribute", "global::JetBrains.Annotations.AspMvcDisplayTemplateAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcEditorTemplateAttribute", "global::JetBrains.Annotations.AspMvcEditorTemplateAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcMasterAttribute", "global::JetBrains.Annotations.AspMvcMasterAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcMasterLocationFormatAttribute", "global::JetBrains.Annotations.AspMvcMasterLocationFormatAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcModelTypeAttribute", "global::JetBrains.Annotations.AspMvcModelTypeAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcPartialViewAttribute", "global::JetBrains.Annotations.AspMvcPartialViewAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcPartialViewLocationFormatAttribute", "global::JetBrains.Annotations.AspMvcPartialViewLocationFormatAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcSuppressViewErrorAttribute", "global::JetBrains.Annotations.AspMvcSuppressViewErrorAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcTemplateAttribute", "global::JetBrains.Annotations.AspMvcTemplateAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcViewAttribute", "global::JetBrains.Annotations.AspMvcViewAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcViewComponentAttribute", "global::JetBrains.Annotations.AspMvcViewComponentAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcViewComponentViewAttribute", "global::JetBrains.Annotations.AspMvcViewComponentViewAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcViewComponentViewLocationFormatAttribute", "global::JetBrains.Annotations.AspMvcViewComponentViewLocationFormatAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspMvcViewLocationFormatAttribute", "global::JetBrains.Annotations.AspMvcViewLocationFormatAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspRequiredAttributeAttribute", "global::JetBrains.Annotations.AspRequiredAttributeAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspRouteConventionAttribute", "global::JetBrains.Annotations.AspRouteConventionAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspRouteOrderAttribute", "global::JetBrains.Annotations.AspRouteOrderAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspRouteValuesConstraintsAttribute", "global::JetBrains.Annotations.AspRouteValuesConstraintsAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspRouteVerbsAttribute", "global::JetBrains.Annotations.AspRouteVerbsAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AspTypePropertyAttribute", "global::JetBrains.Annotations.AspTypePropertyAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AssertionConditionAttribute", "global::JetBrains.Annotations.AssertionConditionAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.AssertionMethodAttribute", "global::JetBrains.Annotations.AssertionMethodAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.BaseTypeRequiredAttribute", "global::JetBrains.Annotations.BaseTypeRequiredAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.CanBeNullAttribute", "global::JetBrains.Annotations.CanBeNullAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.CannotApplyEqualityOperatorAttribute", "global::JetBrains.Annotations.CannotApplyEqualityOperatorAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.CodeTemplateAttribute", "global::JetBrains.Annotations.CodeTemplateAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.CollectionAccessAttribute", "global::JetBrains.Annotations.CollectionAccessAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.ContractAnnotationAttribute", "global::JetBrains.Annotations.ContractAnnotationAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.CqrsCommandAttribute", "global::JetBrains.Annotations.CqrsCommandAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.CqrsCommandHandlerAttribute", "global::JetBrains.Annotations.CqrsCommandHandlerAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.CqrsExcludeFromAnalysisAttribute", "global::JetBrains.Annotations.CqrsExcludeFromAnalysisAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.CqrsQueryAttribute", "global::JetBrains.Annotations.CqrsQueryAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.CqrsQueryHandlerAttribute", "global::JetBrains.Annotations.CqrsQueryHandlerAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.DebuggerGlobalWatchAttribute", "global::JetBrains.Annotations.DebuggerGlobalWatchAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.DefaultEqualityUsageAttribute", "global::JetBrains.Annotations.DefaultEqualityUsageAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.HandlesResourceDisposalAttribute", "global::JetBrains.Annotations.HandlesResourceDisposalAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.HtmlAttributeValueAttribute", "global::JetBrains.Annotations.HtmlAttributeValueAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.HtmlElementAttributesAttribute", "global::JetBrains.Annotations.HtmlElementAttributesAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.IgnoreSpellingAndGrammarErrorsAttribute", "global::JetBrains.Annotations.IgnoreSpellingAndGrammarErrorsAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.InstantHandleAttribute", "global::JetBrains.Annotations.InstantHandleAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.InvokerParameterNameAttribute", "global::JetBrains.Annotations.InvokerParameterNameAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.ItemCanBeNullAttribute", "global::JetBrains.Annotations.ItemCanBeNullAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.ItemNotNullAttribute", "global::JetBrains.Annotations.ItemNotNullAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.LanguageInjectionAttribute", "global::JetBrains.Annotations.LanguageInjectionAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.LinqTunnelAttribute", "global::JetBrains.Annotations.LinqTunnelAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.LocalizationRequiredAttribute", "global::JetBrains.Annotations.LocalizationRequiredAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.MacroAttribute", "global::JetBrains.Annotations.MacroAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.MeansImplicitUseAttribute", "global::JetBrains.Annotations.MeansImplicitUseAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.MeansTestSubjectAttribute", "global::JetBrains.Annotations.MeansTestSubjectAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.MustDisposeResourceAttribute", "global::JetBrains.Annotations.MustDisposeResourceAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.MustUseReturnValueAttribute", "global::JetBrains.Annotations.MustUseReturnValueAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.NoEnumerationAttribute", "global::JetBrains.Annotations.NoEnumerationAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.NoReorderAttribute", "global::JetBrains.Annotations.NoReorderAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.NonNegativeValueAttribute", "global::JetBrains.Annotations.NonNegativeValueAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.NotNullAttribute", "global::JetBrains.Annotations.NotNullAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.NotifyPropertyChangedInvocatorAttribute", "global::JetBrains.Annotations.NotifyPropertyChangedInvocatorAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.PathReferenceAttribute", "global::JetBrains.Annotations.PathReferenceAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.ProvidesContextAttribute", "global::JetBrains.Annotations.ProvidesContextAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.PublicAPIAttribute", "global::JetBrains.Annotations.PublicAPIAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.PureAttribute", "global::JetBrains.Annotations.PureAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.RazorDirectiveAttribute", "global::JetBrains.Annotations.RazorDirectiveAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.RazorHelperCommonAttribute", "global::JetBrains.Annotations.RazorHelperCommonAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.RazorImportNamespaceAttribute", "global::JetBrains.Annotations.RazorImportNamespaceAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.RazorInjectionAttribute", "global::JetBrains.Annotations.RazorInjectionAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.RazorLayoutAttribute", "global::JetBrains.Annotations.RazorLayoutAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.RazorPageBaseTypeAttribute", "global::JetBrains.Annotations.RazorPageBaseTypeAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.RazorSectionAttribute", "global::JetBrains.Annotations.RazorSectionAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.RazorWriteLiteralMethodAttribute", "global::JetBrains.Annotations.RazorWriteLiteralMethodAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.RazorWriteMethodAttribute", "global::JetBrains.Annotations.RazorWriteMethodAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.RazorWriteMethodParameterAttribute", "global::JetBrains.Annotations.RazorWriteMethodParameterAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.RegexPatternAttribute", "global::JetBrains.Annotations.RegexPatternAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.RequireStaticDelegateAttribute", "global::JetBrains.Annotations.RequireStaticDelegateAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.RouteParameterConstraintAttribute", "global::JetBrains.Annotations.RouteParameterConstraintAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.RouteTemplateAttribute", "global::JetBrains.Annotations.RouteTemplateAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.SourceTemplateAttribute", "global::JetBrains.Annotations.SourceTemplateAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.StringFormatMethodAttribute", "global::JetBrains.Annotations.StringFormatMethodAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.StructuredMessageTemplateAttribute", "global::JetBrains.Annotations.StructuredMessageTemplateAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.TerminatesProgramAttribute", "global::JetBrains.Annotations.TerminatesProgramAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.TestSubjectAttribute", "global::JetBrains.Annotations.TestSubjectAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.UriStringAttribute", "global::JetBrains.Annotations.UriStringAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.UsedImplicitlyAttribute", "global::JetBrains.Annotations.UsedImplicitlyAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.ValueProviderAttribute", "global::JetBrains.Annotations.ValueProviderAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.ValueRangeAttribute", "global::JetBrains.Annotations.ValueRangeAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.XamlItemBindingOfItemsControlAttribute", "global::JetBrains.Annotations.XamlItemBindingOfItemsControlAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.XamlItemStyleOfItemsControlAttribute", "global::JetBrains.Annotations.XamlItemStyleOfItemsControlAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.XamlItemsControlAttribute", "global::JetBrains.Annotations.XamlItemsControlAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.XamlOneWayBindingModeByDefaultAttribute", "global::JetBrains.Annotations.XamlOneWayBindingModeByDefaultAttribute"), 
                            new(ServiceLifetime.Transient, "global::JetBrains.Annotations.XamlTwoWayBindingModeByDefaultAttribute", "global::JetBrains.Annotations.XamlTwoWayBindingModeByDefaultAttribute"), 
                            new(ServiceLifetime.Transient, "global::Microsoft.CodeAnalysis.EmbeddedAttribute", "global::Microsoft.CodeAnalysis.EmbeddedAttribute"), 
                            new(ServiceLifetime.Transient, "global::Polyfills.Polyfill+GroupJoinGrouping<,>", "global::Polyfills.Polyfill+GroupJoinGrouping<,>"), 
                            new(ServiceLifetime.Transient, "global::Polyfills.Polyfill+KeySelectorEqualityComparer<,>", "global::Polyfills.Polyfill+KeySelectorEqualityComparer<,>"), 
                            new(ServiceLifetime.Transient, "global::Specular.Abstractions.ExcludeFromSpecularAttribute", "global::Specular.Abstractions.ExcludeFromSpecularAttribute"), 
                            new(ServiceLifetime.Transient, "{scrubbed}"), 
                            new(ServiceLifetime.Transient, "global::Specular.Diagnostics.AssemblyScanReport", "global::Specular.Diagnostics.AssemblyScanReport"), 
                            new(ServiceLifetime.Transient, "global::Specular.Diagnostics.AssemblyScanReportEntry", "global::Specular.Diagnostics.AssemblyScanReportEntry"), 
                            new(ServiceLifetime.Transient, "global::Specular.Diagnostics.ScanResults", "global::Specular.Diagnostics.ScanResults"), 
                            new(ServiceLifetime.Transient, "global::Specular.Diagnostics.ServiceDescriptorAssemblyScanReportEntry", "global::Specular.Diagnostics.ServiceDescriptorAssemblyScanReportEntry"), 
                            new(ServiceLifetime.Transient, "global::Specular.Diagnostics.ServiceDescriptorScanReport", "global::Specular.Diagnostics.ServiceDescriptorScanReport"), 
                            new(ServiceLifetime.Transient, "global::Specular.Diagnostics.ServiceDescriptorScanReportEntry", "global::Specular.Diagnostics.ServiceDescriptorScanReportEntry"), 
                            new(ServiceLifetime.Transient, "global::Specular.Diagnostics.TypeScanAssemblyReportEntry", "global::Specular.Diagnostics.TypeScanAssemblyReportEntry"), 
                            new(ServiceLifetime.Transient, "global::Specular.Diagnostics.TypeScanReport", "global::Specular.Diagnostics.TypeScanReport"), 
                            new(ServiceLifetime.Transient, "global::Specular.Diagnostics.TypeScanReportEntry", "global::Specular.Diagnostics.TypeScanReportEntry"), 
                            new(ServiceLifetime.Transient, "global::Specular.RegistrationLifetimeAttribute", "global::Specular.RegistrationLifetimeAttribute"), 
                            new(ServiceLifetime.Transient, "global::Specular.ServiceRegistrationAttribute", "global::Specular.ServiceRegistrationAttribute"), 
                            new(ServiceLifetime.Transient, "global::Specular.ServiceRegistrationAttribute<,,,,,,,>", "global::Specular.ServiceRegistrationAttribute<,,,,,,,>"), 
                            new(ServiceLifetime.Transient, "global::Specular.ServiceRegistrationAttribute<,,,,,,>", "global::Specular.ServiceRegistrationAttribute<,,,,,,>"), 
                            new(ServiceLifetime.Transient, "global::Specular.ServiceRegistrationAttribute<,,,,,>", "global::Specular.ServiceRegistrationAttribute<,,,,,>"), 
                            new(ServiceLifetime.Transient, "global::Specular.ServiceRegistrationAttribute<,,,,>", "global::Specular.ServiceRegistrationAttribute<,,,,>"), 
                            new(ServiceLifetime.Transient, "global::Specular.ServiceRegistrationAttribute<,,,>", "global::Specular.ServiceRegistrationAttribute<,,,>"), 
                            new(ServiceLifetime.Transient, "global::Specular.ServiceRegistrationAttribute<,,>", "global::Specular.ServiceRegistrationAttribute<,,>"), 
                            new(ServiceLifetime.Transient, "global::Specular.ServiceRegistrationAttribute<,>", "global::Specular.ServiceRegistrationAttribute<,>"), 
                            new(ServiceLifetime.Transient, "global::Specular.ServiceRegistrationAttribute<>", "global::Specular.ServiceRegistrationAttribute<>"), 
                            new(ServiceLifetime.Transient, "global::SpecularProvider", "global::SpecularProvider"), 
                            new(ServiceLifetime.Transient, "global::SpecularScanReport", "global::SpecularScanReport"), 
                            new(ServiceLifetime.Transient, "global::System.Buffers.ReadOnlySequenceStream", "global::System.Buffers.ReadOnlySequenceStream"), 
                            new(ServiceLifetime.Transient, "global::System.Diagnostics.ProcessExitStatus", "global::System.Diagnostics.ProcessExitStatus"), 
                            new(ServiceLifetime.Transient, "global::System.Diagnostics.ProcessTextOutput", "global::System.Diagnostics.ProcessTextOutput"), 
                            new(ServiceLifetime.Transient, "global::System.IO.ReadOnlyMemoryStream", "global::System.IO.ReadOnlyMemoryStream"), 
                            new(ServiceLifetime.Transient, "global::System.IO.StringStream", "global::System.IO.StringStream"), 
                            new(ServiceLifetime.Transient, "global::System.IO.WritableMemoryStream", "global::System.IO.WritableMemoryStream")]
                    ), 
                    new("System.Collections.Immutable", 
                        [
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.DefaultFrozenDictionary<,>", "global::System.Collections.Frozen.DefaultFrozenDictionary<,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.DefaultFrozenSet<>", "global::System.Collections.Frozen.DefaultFrozenSet<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.DenseIntegralFrozenDictionary", "global::System.Collections.Frozen.DenseIntegralFrozenDictionary"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.DenseIntegralFrozenDictionary+DebuggerProxy<,,>", "global::System.Collections.Frozen.DenseIntegralFrozenDictionary+DebuggerProxy<,,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.DenseIntegralFrozenDictionary+WithFullValues<,,>", "global::System.Collections.Frozen.DenseIntegralFrozenDictionary+WithFullValues<,,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.DenseIntegralFrozenDictionary+WithOptionalValues<,,>", "global::System.Collections.Frozen.DenseIntegralFrozenDictionary+WithOptionalValues<,,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.EmptyFrozenDictionary<,>", "global::System.Collections.Frozen.EmptyFrozenDictionary<,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.EmptyFrozenSet<>", "global::System.Collections.Frozen.EmptyFrozenSet<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.Int32FrozenDictionary<>", "global::System.Collections.Frozen.Int32FrozenDictionary<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.Int32FrozenSet", "global::System.Collections.Frozen.Int32FrozenSet"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.KeyAnalyzer+JustifiedCaseInsensitiveAsciiSubstringComparer", "global::System.Collections.Frozen.KeyAnalyzer+JustifiedCaseInsensitiveAsciiSubstringComparer"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.KeyAnalyzer+JustifiedCaseInsensitiveSubstringComparer", "global::System.Collections.Frozen.KeyAnalyzer+JustifiedCaseInsensitiveSubstringComparer"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.KeyAnalyzer+JustifiedSubstringComparer", "global::System.Collections.Frozen.KeyAnalyzer+JustifiedSubstringComparer"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.LengthBucketsFrozenDictionary<>", "global::System.Collections.Frozen.LengthBucketsFrozenDictionary<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.LengthBucketsFrozenSet", "global::System.Collections.Frozen.LengthBucketsFrozenSet"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_Full<>", "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_Full<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_FullCaseInsensitive<>", "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_FullCaseInsensitive<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_FullCaseInsensitiveAscii<>", "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_FullCaseInsensitiveAscii<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_LeftJustifiedCaseInsensitiveAsciiSubstring<>", "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_LeftJustifiedCaseInsensitiveAsciiSubstring<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_LeftJustifiedCaseInsensitiveSubstring<>", "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_LeftJustifiedCaseInsensitiveSubstring<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_LeftJustifiedSingleChar<>", "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_LeftJustifiedSingleChar<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_LeftJustifiedSubstring<>", "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_LeftJustifiedSubstring<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_RightJustifiedCaseInsensitiveAsciiSubstring<>", "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_RightJustifiedCaseInsensitiveAsciiSubstring<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_RightJustifiedCaseInsensitiveSubstring<>", "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_RightJustifiedCaseInsensitiveSubstring<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_RightJustifiedSingleChar<>", "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_RightJustifiedSingleChar<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_RightJustifiedSubstring<>", "global::System.Collections.Frozen.OrdinalStringFrozenDictionary_RightJustifiedSubstring<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenSet_Full", "global::System.Collections.Frozen.OrdinalStringFrozenSet_Full"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenSet_FullCaseInsensitive", "global::System.Collections.Frozen.OrdinalStringFrozenSet_FullCaseInsensitive"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenSet_FullCaseInsensitiveAscii", "global::System.Collections.Frozen.OrdinalStringFrozenSet_FullCaseInsensitiveAscii"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenSet_LeftJustifiedCaseInsensitiveAsciiSubstring", "global::System.Collections.Frozen.OrdinalStringFrozenSet_LeftJustifiedCaseInsensitiveAsciiSubstring"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenSet_LeftJustifiedCaseInsensitiveSubstring", "global::System.Collections.Frozen.OrdinalStringFrozenSet_LeftJustifiedCaseInsensitiveSubstring"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenSet_LeftJustifiedSingleChar", "global::System.Collections.Frozen.OrdinalStringFrozenSet_LeftJustifiedSingleChar"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenSet_LeftJustifiedSubstring", "global::System.Collections.Frozen.OrdinalStringFrozenSet_LeftJustifiedSubstring"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenSet_RightJustifiedCaseInsensitiveAsciiSubstring", "global::System.Collections.Frozen.OrdinalStringFrozenSet_RightJustifiedCaseInsensitiveAsciiSubstring"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenSet_RightJustifiedCaseInsensitiveSubstring", "global::System.Collections.Frozen.OrdinalStringFrozenSet_RightJustifiedCaseInsensitiveSubstring"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenSet_RightJustifiedSingleChar", "global::System.Collections.Frozen.OrdinalStringFrozenSet_RightJustifiedSingleChar"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.OrdinalStringFrozenSet_RightJustifiedSubstring", "global::System.Collections.Frozen.OrdinalStringFrozenSet_RightJustifiedSubstring"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.SmallFrozenDictionary<,>", "global::System.Collections.Frozen.SmallFrozenDictionary<,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.SmallFrozenSet<>", "global::System.Collections.Frozen.SmallFrozenSet<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.SmallValueTypeComparableFrozenDictionary<,>", "global::System.Collections.Frozen.SmallValueTypeComparableFrozenDictionary<,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.SmallValueTypeComparableFrozenSet<>", "global::System.Collections.Frozen.SmallValueTypeComparableFrozenSet<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.SmallValueTypeDefaultComparerFrozenDictionary<,>", "global::System.Collections.Frozen.SmallValueTypeDefaultComparerFrozenDictionary<,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.SmallValueTypeDefaultComparerFrozenSet<>", "global::System.Collections.Frozen.SmallValueTypeDefaultComparerFrozenSet<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.ValueTypeDefaultComparerFrozenDictionary<,>", "global::System.Collections.Frozen.ValueTypeDefaultComparerFrozenDictionary<,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Frozen.ValueTypeDefaultComparerFrozenSet<>", "global::System.Collections.Frozen.ValueTypeDefaultComparerFrozenSet<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Generic.IDictionaryDebugView<,>", "global::System.Collections.Generic.IDictionaryDebugView<,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.DictionaryEnumerator<,>", "global::System.Collections.Immutable.DictionaryEnumerator<,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableArray<T>+Builder<>", "global::System.Collections.Immutable.ImmutableArray<T>+Builder<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableArray<T>+EnumeratorObject<>", "global::System.Collections.Immutable.ImmutableArray<T>+EnumeratorObject<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableArrayBuilderDebuggerProxy<>", "global::System.Collections.Immutable.ImmutableArrayBuilderDebuggerProxy<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableDictionary<,>", "global::System.Collections.Immutable.ImmutableDictionary<,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableDictionary<TKey, TValue>+Builder<>", "global::System.Collections.Immutable.ImmutableDictionary<TKey, TValue>+Builder<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableDictionary<TKey, TValue>+Comparers<>", "global::System.Collections.Immutable.ImmutableDictionary<TKey, TValue>+Comparers<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableDictionaryDebuggerProxy<,>", "global::System.Collections.Immutable.ImmutableDictionaryDebuggerProxy<,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableEnumerableDebuggerProxy<>", "global::System.Collections.Immutable.ImmutableEnumerableDebuggerProxy<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableExtensions+FallbackWrapper<>", "global::System.Collections.Immutable.ImmutableExtensions+FallbackWrapper<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableExtensions+ListOfTWrapper<>", "global::System.Collections.Immutable.ImmutableExtensions+ListOfTWrapper<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableHashSet<>", "global::System.Collections.Immutable.ImmutableHashSet<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableHashSet<T>+Builder<>", "global::System.Collections.Immutable.ImmutableHashSet<T>+Builder<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableHashSet<T>+HashBucketByRefEqualityComparer<>", "global::System.Collections.Immutable.ImmutableHashSet<T>+HashBucketByRefEqualityComparer<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableHashSet<T>+HashBucketByValueEqualityComparer<>", "global::System.Collections.Immutable.ImmutableHashSet<T>+HashBucketByValueEqualityComparer<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableList<>", "global::System.Collections.Immutable.ImmutableList<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableList<T>+Builder<>", "global::System.Collections.Immutable.ImmutableList<T>+Builder<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableList<T>+Node<>", "global::System.Collections.Immutable.ImmutableList<T>+Node<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableListBuilderDebuggerProxy<>", "global::System.Collections.Immutable.ImmutableListBuilderDebuggerProxy<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableQueue<>", "global::System.Collections.Immutable.ImmutableQueue<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableQueue<T>+EnumeratorObject<>", "global::System.Collections.Immutable.ImmutableQueue<T>+EnumeratorObject<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableSortedDictionary<,>", "global::System.Collections.Immutable.ImmutableSortedDictionary<,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableSortedDictionary<TKey, TValue>+Builder<>", "global::System.Collections.Immutable.ImmutableSortedDictionary<TKey, TValue>+Builder<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableSortedDictionary<TKey, TValue>+Node<>", "global::System.Collections.Immutable.ImmutableSortedDictionary<TKey, TValue>+Node<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableSortedSet<>", "global::System.Collections.Immutable.ImmutableSortedSet<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableSortedSet<T>+Builder<>", "global::System.Collections.Immutable.ImmutableSortedSet<T>+Builder<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableSortedSet<T>+Node<>", "global::System.Collections.Immutable.ImmutableSortedSet<T>+Node<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableSortedSet<T>+ReverseEnumerable<>", "global::System.Collections.Immutable.ImmutableSortedSet<T>+ReverseEnumerable<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableSortedSetBuilderDebuggerProxy<>", "global::System.Collections.Immutable.ImmutableSortedSetBuilderDebuggerProxy<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableStack<>", "global::System.Collections.Immutable.ImmutableStack<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ImmutableStack<T>+EnumeratorObject<>", "global::System.Collections.Immutable.ImmutableStack<T>+EnumeratorObject<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.KeysCollectionAccessor<,>", "global::System.Collections.Immutable.KeysCollectionAccessor<,>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.SecurePooledObject<>", "global::System.Collections.Immutable.SecurePooledObject<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.SortedInt32KeyNode<>", "global::System.Collections.Immutable.SortedInt32KeyNode<>"), 
                            new(ServiceLifetime.Transient, "global::System.Collections.Immutable.ValuesCollectionAccessor<,>", "global::System.Collections.Immutable.ValuesCollectionAccessor<,>"), 
                            new(ServiceLifetime.Transient, "global::System.Runtime.Versioning.NonVersionableAttribute", "global::System.Runtime.Versioning.NonVersionableAttribute")]
                    ), 
                    new("System.ComponentModel", 
                        [
                            new(ServiceLifetime.Transient, "global::System.ComponentModel.CancelEventArgs", "global::System.ComponentModel.CancelEventArgs")]
                    ), 
                    new("TestProject", 
                        [
                            new(ServiceLifetime.Transient, "global::Microsoft.CodeAnalysis.EmbeddedAttribute", "global::Microsoft.CodeAnalysis.EmbeddedAttribute"), 
                            new(ServiceLifetime.Transient, "global::Service", "global::Service")]
                    )]
            )]
    );
}